### ISSUE TITLE
フロントエンジニア強化施策 フェーズ1報告

### ISSUE THREAD

**Issue by nametake55** [ykk-yos1982/yayoi#13]
# フロントエンジニア強化施策 フェーズ1報告

### 言語やツールの理解  
* フロント周りを構築する主要な言語について、メンバー全員が基本的な文法や作法を理解するレベルに達したと思われる。
* HTMLやCSSは比較的文法が分かりやすい言語であったため、「ほぼノーヒントで各々が調べながら進める方針」でも大きな問題はなかったと思われる。
* エンジニアのスキルレベルが異なるため、他言語のスキルレベルが高いエンジニアにとっては少し物足りない課題となったかもしれない。
* 当施策では成果物を完成させる事だけでなく、作業中のプロセスやつまづいた点をアウトプットする点も重視していた。そのため各々のレベルでのつまづきや解決方法をを全員で共有できたため、施策の目的としては達成できたと考えられる。  

### Slack
* メールより気軽にコミュニケーションが取りやすく、有用なツールだと感じた。
* メンバーが不明点や作業状況のやりとりをする会話がオープンになることで、取り組みのモチベーションが上がる点もメリットと感じる。
* フェーズ1の段階では、十分に活用できたとは言えない。メンバによって発言量が異なるため、全体的にコミュニケーション量が増えるか模索が必要。
* 業務での利用にそのまま転用できるかは、以下の点に追いて課題あり。
  * 発言量が多いと、情報が流れてしまいがち。（今回の取り組みの中でも、Slackで展開済の内容について質問が出るなど、内容の見漏れが発生していた。）
  →全体への連絡事項など、必ず全員で共有すべき内容は、別途連絡が必要。
  * 業務で利用した際、素早い反応が求められる内容をやりとりすることになると、常にSlackに意識を払っておく必要があり、集中する作業に支障がでる恐れもあると感じる。
  今回の取り組みでは「原則定時後の作業を行う」グランドルールがあったため、時間内でSlackを利用するケースが少なく、そこまで気になる事はなかった。
  →緊急性の高い内容と、そうでない内容をやりとりするグループを分けるか、緊急性の高い内容はSlackを利用しないルールを設ける等の工夫が必要と思われる。

### 成果発表会
* 若手メンバは、まだ業務で他者のソースレビューを行う機会がない。ソースを見比べて、どのような書き方がよいか考える良い機会。中堅のメンバが参加者に含まれている点で、見本となるソースが展開される点が非常に良かった。
（このような勉強会は、若手だけが参加 になりがちであるため。）
* 成果発表会に、参加者の上位者が参加することで、レビューがだらけたものにならずに良かったと思われる。参加者だけだと互いに作業している内容が分かっているため、「他者に説明する」良い緊張感があった。
* 自分が取り組んできた内容について正確に理解して説明する必要があるため、取り組みの内容を整理するためにも良い効果があったと思われる。

## 改善が必要な点
* 成果発表会の際に、お互いの良い点悪い点を付箋に書いて渡す等、意見交換のアウトプットを残せるようなやり方を検討したい。
* フェーズ1は、与えられた課題をこなす感がでてしまった。フェーズ2は、もう少し楽しみながら、各チーム毎にアイデアを出しながら進められるとよい。（フェーズ2は、取り組みの大枠だけ決めて、自由な内容で実施してもらうようにする。）
* チーム間でのコミュニケーションが物足りなかった。もう少し話し合いながらできてもよい。

## 参考情報
* [フェーズ1成果発表 議事](https://github.com/ykk-yos1982/yayoi/issues/8)

**Comment by ykk-yos1982** [comment]
参加者のみなさんお疲れ様でした。

今回はシンプルなレスポンシブ対応のHTMLマークアップでしたが、
・様々なレイアウト方法
・ブラウザ互換性
について技術課題を設定してみました。（私の腹づもりとして）

思ったよりもシンプルなHTMLながら想像以上に苦戦したことと思います。

ブラウザに付属の開発社ツールを活用することで、
デバッグの手間を大きく減らすことができます。

コーディング、保存、ブラウザリロードよりも、
開発者ツールで、即時HTMLを直接書き換えるほうが早いことが多いです。
ぜひ、活用してください。

float、flexでの配置方法から、スタイルシートの当て方など
本当に多種多様で興味深い内容になりました。
自分がハマったところなど、他者のソースコードを見て参考にしてください。

Slackのチャンネル運用は、
本来的にはトピックやテーマごとにチャンネルを分けたりします。（本部のリーダーは色々使いわけてます）

あくまでも今回は、お互いのコミュニケーションを活性させるための手段や情報共有、コミュニケーションをOpenにすることの意義を感じていただければと思います。
フェーズ２では、もっと活用してください。
あと、重要な連絡事項は、ピン留めをしてメンバーが常に見える形で掲示することも可能です。
ぜひ活用してみてください。

あと、各チームごとに開発者BLOGへの投稿をお願いします。

まずは、チーム２（狩野さん、藤井さん）からよろしくおねがいします。

**Comment by nametake55** [comment]
フロントエンジニア強化施策 第2回開催のため、第1回のissueはクローズします。
