### ISSUE TITLE
ふりかえりの実施

### ISSUE THREAD

**Issue by nametake55** [ykk-yos1982/yayoi#15]
### ふりかえりの日程
3/23(木) 18:00～19:30

### 内容  
1. 観点  
   * 運営の観点（狩野さん、植竹のみ）  
   * 参加者の観点（全員）
1. 内容  
   * よかったこと、続けたいこと  
   * よくなかったこと、改善したいこと  
   * 上記から継続して試したいこと    
1. やり方
   * ～3/22 各自xmindで整理する（「事象」の列挙まで）  
   * 3/23 全員で共有する（「課題」、「施策」を洗い出し）  
1. 補足  
上記の内容で「事象」の列挙を行い、xmindにまとめてください。
23日に全員で集まり、「課題」、「施策」について検討します。
※「課題」、「施策」まで落とし込める内容があれば、そこまで各自でまとめてきてもらって構いません。

**Comment by nametake55** [comment]
xmind保管場所について補足

**Comment by ykk-yos1982** [comment]
冒頭にふりかえりの方法について説明する時間を設けます。

**Comment by nametake55** [comment]
フロントエンジニア強化施策 第2回開催のため、第1回のissueはクローズします。
