### ISSUE TITLE
自由課題アンケート（uetk）

### ISSUE THREAD

**Issue by nametake55** [ykk-yos1982/yayoi#22]

**Comment by nametake55** [comment]
1. 現状のフロントの技術の習得度  
（例）CSSを調べつつ書けるレベル  

1. この施策の中で習得したいもの  
（例）Sassが書けるようになりたい  

1. フロントの技術を使って作りたいもの、やりたいこと  
（例）グリッドデザインを使って画面を作りたい

1. その他  
なにかあれば

**Comment by oha-ryo-y2i** [comment]
1.現状のフロントの技術の習得度
HTML：一通りの要素と属性を網羅し、非推奨になっているものは使わないように意識できる。ただし、アウトライン設計には疎い。
CSS：調べれば多少は書けるが、基礎ができていない。Scssやフレームワークにも疎い。
JavaScript：基本的な設計思想を理解し、思った通りの実装は概ねできる。jQeuryも使うことができる。

2.この施策の中で習得したいもの
・cssのコンポーネント設計
・cssのフレームワーク利用方法（例：MaterialDesignLite）
・Scss
・htmlコーディングのベストプラクティス

3.フロントの技術を使って作りたいもの、やりたいこと
社内のフロントエンジニアチームに所属しているので、業務で活用する
トレンドなデザインのチャットアプリケーションの自主開発
上記以外のWebアプリケーションの自主開発（思案中だが、レビューサイトや予約サイトを作ってみたい）

4.その他
自主的にflexbox,Scss,jQueryを利用した簡単なページを作成してみました。遊び心でgradientも使ってみました。
https://github.com/ykk-yos1982/yayoi/blob/pre_training/pre_training/oha/templates/flexbox/test.html

**Comment by Dkano0000** [comment]
1. フロントの技術の習得度
CSSは調べつつ書けるレベル
javascriptは調べればかけるレベル
・業務ではtypescriptを使用している
・JQueryはwijmo5を使用しているため業務上あまり触れる機会はなく、調べれば実装できる程度
HTMLは調べればかけるレベル
・業務ではレイアウトの微調整程度

2. この施策の中で習得したいもの
・Sass（Sassは経験なし）
　⇒Sassの特徴などをつかみたい
・GitHub（使用経験なし）
・フロントサイドの作法（べからず的な話も）

3. フロントの技術を使って作りたいもの、やりたいこと
作りたい具体的なアプリケーションのイメージは特になし。
・アニメーション
<https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Animations/Using_CSS_animations>
・CSSだけで機能をもたせる
　（例）CSSだけで開閉できるアコーディオン
<http://qiita.com/takanorip/items/217f9c29715825de0fdc>

4. その他
Sassを調べるとCompassがかなりおすすめされている。
自由課題で使ってみたい。
<https://www.tam-tam.co.jp/tipsnote/html_css/post5189.html>
