### ISSUE TITLE
Branchきれないアクセス権限の問題の可能性あり

### ISSUE THREAD

**Issue by Dkano0000** [ykk-yos1982/yayoi#28]
### Branchきれませんでした
* アクセス権限が無い可能性があります

**Comment by TomoeAizawa** [comment]
私もできません。

**Comment by ykk-yos1982** [comment]
コラボレーターとして、登録したので再度確認をお願いします。

**Comment by Dkano0000** [comment]
再度確認しましたが、プッシュできませんでした。
エラーメッセージは下記の通りです。
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=manager-st push -v --tags origin master:master
Logon failed, use ctrl+c to cancel basic credential prompt.
remote: Permission to ykk-yos1982/yayoi.git denied to Dkano0000.
fatal: unable to access 'https://github.com/ykk-yos1982/yayoi.git/': The requested URL returned error: 403

Pushing to https://github.com/ykk-yos1982/yayoi.git

Pushing to https://github.com/ykk-yos1982/yayoi.git
エラー終了しました。エラーの内容は上記をご覧ください。

**Comment by Dkano0000** [comment]
Acceptしてないだけでした。
プッシュできました。

**Comment by Dkano0000** [comment]
対応ありがとうございます。

**Comment by ykk-yos1982** [comment]
了解です。

**Comment by ykk-yos1982** [comment]
他の人も問題なければクローズしてくださいね

**Comment by TomoeAizawa** [comment]
コミットできました。
対応ありがとうございます。

**Comment by YYItrmk** [comment]
@ykk-yos1982 リポジトリの権限の付与をお願いいたします。

**Comment by ykk-yos1982** [comment]
@YYItrmk 確認遅れました、今追加しました。

**Comment by oha-ryo-y2i** [comment]
私も権限問題ありません。

@YYItrmk 
昨日の成果物のプッシュが成功したら本issueのクローズをお願いします。

**Comment by YYItrmk** [comment]
@ykk-yos1982  対応ありがとうございます。昨日の成果物をプッシュできました。
クローズします。
