### ISSUE TITLE
チーム2：PCサイズのレイアウトを作成する

### ISSUE THREAD

**Issue by keisukeKarino** [ykk-yos1982/yayoi#3]
#### 【概要】
* まずは、レスポンシブデザインを意識せず、
カンプ内のPCサイズと同じになるように要素を配置してみる。

#### 【メモ】
* ここにつまづいたこととか書いてく。

**Comment by SatokoFujii0119** [comment]
つまづいていること
・コンテンツ5がコンテンツ2の下にいってしまう
・縦書きにした時に文字が右寄せになる
　・数字だけ横向きになる

**Comment by SatokoFujii0119** [comment]
数字だけ横向きになるのは修正できました。
コンテンツ5がコンテンツ2の下に行ってしまうのは全体の横幅を99%とすることで回避しています。

縦書き位置の調整の方法が不明です。

**Comment by keisukeKarino** [comment]
コンテンツの配置は、flexboxを使用して実現してみてください。
このサイトが参考になるかと思います。

<http://coliss.com/articles/build-websites/operation/css/css3-flexbox-properties-by-scotch.html>

まずは、コンテンツ２とコンテンツ３、４、５で分けてその後に
コンテンツ３、４、５の方にflexboxのスタイルを当てることになるかと思います。

**Comment by keisukeKarino** [comment]
昨日いっていた文字の中央寄せの対応をコミットしました。  
変更点を見ておいてください。

**Comment by keisukeKarino** [comment]
contentMenuにあてているheight:100%が悪さをしているかも。
下記サイトが修正にあたり参考になるかもしれません。

<http://qiita.com/hashrock/items/939684b9207dbab1d59e>

**Comment by SatokoFujii0119** [comment]
教えて頂いたサイトを参考にしてhtml、cssを修正しました。
すべてのコンテンツを囲うことで解消できました。

**Comment by keisukeKarino** [comment]
IEは、縦書きを想定している箇所が、横書きになっていました。
writing-modeにしている値が他のブラウザとは異なるようです。
<http://www.htmq.com/style/writing-mode.shtml>

**Comment by keisukeKarino** [comment]
上記コメントのサイトの指定方法は、すべてのブラウザで解釈できるので、
置き換えれば直りそうです。

**Comment by SatokoFujii0119** [comment]
明日の朝、確認して対応します。

**Comment by SatokoFujii0119** [comment]
IEで縦書きになるように修正したものをコミットしました。

**Comment by SatokoFujii0119** [comment]
ブレイクポイントがおかしいことによりIEでのレイアウトが崩れます。
調整しようとしましたが、上手くできませんでした。

**Comment by keisukeKarino** [comment]
了解です。
