### ISSUE TITLE
ペアプログラミングの実施方針について

### ISSUE THREAD

**Issue by oha-ryo-y2i** [ykk-yos1982/yayoi#30]
＞uetkさん
ペアプログラミングの実施経験がないので、
ペアプログラミングの概要、方法、ベストプラクティス、注意点、メリット、デメリット、参考にすると良いサイト
などを経験者として教えていただけると嬉しいです。

**Comment by ykk-yos1982** [comment]
@oha-ryo-y2i 
弥生の社内報を参考にしてみてください。
石下さんが良いレポートしてくれています。これを読んだ上で聞きたいことがあれば
その箇所を明確にして質問をお願いします。
https://compass.yayoi-kk.co.jp/2017/04/14/issi_misoca-report_vol-1/

**Comment by oha-ryo-y2i** [comment]
@ykk-yos1982 
ありがとうございます。
参考URLの内容で理解・イメージ出来ました。
