### ISSUE TITLE
Gitの運用について

### ISSUE THREAD

**Issue by oha-ryo-y2i** [ykk-yos1982/yayoi#31]
＞uetkさん
→wikiに「training以下にチームごとにフォルダを用意していますので、そちらをご利用ください」とありますが、現在は用意されていないようなので、ご用意お願いします。

また、運用について以下のことを教えてください。
1.ブランチはmasterブランチで運用するか、各自新しいブランチを作成の上で運用するか
1-1.（新しいブランチを作成する場合）ブランチ名の命名規則
1-2.（新しいブランチを作成する場合）ブランチ作成はチーム単位か、作業者単位か
以上です。

**Comment by nametake55** [comment]
今回チーム毎のフォルダは各チームで作成をお願いします(wikiが古かったので修正しておきます)

1.ブランチはきらず、masterブランチにプッシュでokです

**Comment by oha-ryo-y2i** [comment]
@nametake55 
masterブランチでの運用了解しました。
