### ISSUE TITLE
「css_trainingのルール」の章が見つかりません

### ISSUE THREAD

**Issue by Dkano0000** [ykk-yos1982/yayoi#32]

**Comment by Dkano0000** [comment]
下記ページの「課題の概要」に記載されている「css_trainingのルール」の章がみつかりません。
ご確認お願いいたします。
http://noel.yayoi-kk.co.jp/FASTUX/src/tree/master/FrontEngTraining/1_TeachingMaterials/Phase1/1-2_Responsive

**Comment by nametake55** [comment]
こちら以下の誤りでした。  
* トレーニングのルールや制約事項は「課題のルール」の章を参照する  

wikiは後程修正いたします。ご確認ありがとうございます。

**Comment by Dkano0000** [comment]
ご確認いただきありがとうございました。
解決したのでCloseします。
