### ISSUE TITLE
team2の進捗管理

### ISSUE THREAD

**Issue by TomoeAizawa** [ykk-yos1982/yayoi#35]
# 作業内容
・レスポンシブ対応（コンテンツなし）画面作成
・セレクタのトレーニング
・mock作成

**Comment by TomoeAizawa** [comment]
7/11
セレクタのトレーニング作成中です。
・否定セレクタ
・疑似要素
・属性セレクタ
を使用しました。
明日(7/12)課題完了予定です。

**Comment by TomoeAizawa** [comment]
・セレクタのトレーニングを完了しました。

**Comment by Dkano0000** [comment]
セレクタのトレーニングの指摘に対応しました。
