### ISSUE TITLE
セレクタのトレーニングの模範解答が見れない

### ISSUE THREAD

**Issue by TomoeAizawa** [ykk-yos1982/yayoi#39]
wikiの【模範解答】1-4_Selectorのリンクが404になっていて、
模範解答が見れないため、修正をお願い致します。

**Comment by nametake55** [comment]
すみません、こちら格納が漏れていました。
模範解答を追加しました。
（masterにマージされるまでは、「FrontEngTraining_upd」ブランチを参照してください。）
模範解答はSassで記載することを想定しているため、Sassファイルで読み替えて確認してください。
※Sassの記載で不明な点あれば補足しますので、聞いてください。
