### ISSUE TITLE
チーム1：レイアウト作成(PC)

### ISSUE THREAD

**Issue by ykk-yos1982** [ykk-yos1982/yayoi#4]
デザインカンプに従ってPCサイズのHTML/CSSモックを作成する

[カンプは社内に配置](http://ysv-sdsvn-doc:8080/svn/barshu/trunk/000_プロジェクト計画/UX検討/資料/トレーニング/フェーズ1_カンプ.xlsx)

**Comment by masaya-fukuda** [comment]
◆つまずいたこと

・コンテナの淵に余白ができる
　→marginを0pxに指定して解決済

・スマホサイズのときにコンテンツ３，４，５が右側に配置できない（コンテンツ2の下部に潜り込む）
　→float:leftに指定して解決

・スマホサイズのときにコンテンツ３、４、５の右端がコンテンツ１と揃わない
　→widthを分割し、全体で100%となるように指定することで解決済

・メディアクエリがうまく効かない（スマホサイズの時に切り替わらない）
　→記述を修正して解決済

・IEの時のみPCサイズが適用されない
　→http://doshirouto.wp.xdomain.jp/web/css-web/1712　の方法で解決済

◆課題
cssファイルにそれぞれのメディアクエリを記述しているため、コードが冗長
sassを活用する。
→sassを用いてmixinでメディアクエリ記述を集約。色の指定も変数で１箇所に集約。

**Comment by ykk-yos1982** [comment]
http://unskilled.site/sassでメディアクエリをmixinでまとめる/
のあたりを参考に、Sassを導入して効率の良いメディアクエリの書き方をlearnしてください。

**Comment by masaya-fukuda** [comment]
承知いたしました。ありがとうございます。

**Comment by ykk-yos1982** [comment]
@masaya-fukuda 
進捗どうでしょうか。Sass使って今日中に完成させられそうですか。

**Comment by masaya-fukuda** [comment]
@ykk-yos1982  本日の業務時間後より着手予定です。進捗は本日ご報告いたします。

**Comment by ykk-yos1982** [comment]
@masaya-fukuda 承知です。よろしくおねがいします！

**Comment by masaya-fukuda** [comment]
@ykk-yos1982 sassを使用して改善後のコードをコミットしました。

**Comment by ykk-yos1982** [comment]
@masaya-fukuda 
了解です、確認します。

**Comment by ykk-yos1982** [comment]
トレーニングお疲れ様でした。
フィードバックします。

# Sassのネスト記法にTryしてください
こんな感じでcontent2はスッキリさせられます。
まだまだ、効率の良い書き方がありますので、さらなる追求をしてみてはいかがでしょう。

```
#contents{
        float:left; min-height: 600px; overflow: hidden;width:40%;
        
	   .content{
           margin: 0px; height: 600px; background:$color2;
        }

        @include media_query_tablet{
            #contents{
                width:20%;
            }
        }
        @include media_query_pc{
			#contents{
                width:19%;
            }
        }
    }
```

# IDやクラス名の付け方に注意を
クラス名、IDがcontentと重複しているので、可読性の観点で低下しています。
```
			<div id="contents">
				<div class="content">
```
また、なぜ「`<div id="contents">`」でなくてはならないのか。
HTML構造もネストしていますが過剰です。
他のマークアップ構造に合わせるためのように推察しました。

# VisualStudioCodeを活用してください
マークアップのフォーマットで整形するとインデントがつくことで
サイトの構造がわかりやすくなります。

# その他
* 色の指定方法が"black"やHEX表記（6桁、3桁）で混同しています
* `margin: 0px; `を指定している意図が不明瞭でした
`#contents .content{margin: 0px; height: 600px; background:$color2;}`

**Comment by ykk-yos1982** [comment]
確認したらクローズしてください。

**Comment by masaya-fukuda** [comment]
@ykk-yos1982 レビューいただきありがとうございます。
参考にさせていただきます。
