### ISSUE TITLE
ブログ記事：投稿方針

### ISSUE THREAD

**Issue by oha-ryo-y2i** [ykk-yos1982/yayoi#46]
# ブログの投稿方針
* 参加メンバーが持ち回りで投稿
* 一つのトレーニングにつき一人（例外あり）
* 投稿前に運営メンバーにレビュー依頼をする
* 投稿の順序は実施したトレーニングの流れと同じにする

# 投稿内容のコンセプト
* 「外部の人へ弥生内部での取り組みをアピールする」

外部の人とは？
→弥生に興味があって弥生について調べている転職活動中のエンジニアや就活中の学生や、弥生の競合他社のエンジニアを主として想定

# 投稿の流れ
* 記事１：HTML/CSS初挑戦メンバー（相澤）によるトレーニング１（flexboxやセレクタ操作について）の実施完了報告：投稿期限は8/4(金)
* 記事２：HTML/CSS経験メンバー（大橋）によるトレーニング２（カレンダー）の途中経過報告：投稿期限は8/4(金)
* 記事３：HTML/CSS経験メンバー（大橋）によるトレーニング２（カレンダー）の実施完了報告：投稿期限は未定
* 記事４～：未定

# 大筋の記事内容
### 概要
* 実施した施策
  * 参照先としてwikiのURLを記載
* 自己紹介（立場、参加したきっかけ、内部施策への想いなど）
*  **自分のスキルのスタートラインと目標
 　　 スタートラインからこれだけ成長したよってことを最後に書いてつなげてね**
~~・アピールポイント（例：参加メンバーは有志、ペアプロで実施
アプロで実施、flexboxを使っている、など）~~
* メンバー紹介（名前（イニシャル）、立場など）
### 実施
* 成果物のスクリーンショット画像とソースコードURL
*トレーニングを通しての躓きや学び

### まとめ
* **目標の達成度**
* 感想

### 後続記事の紹介
* 次のトレーニングはカレンダーです。など

**Comment by nametake55** [comment]
>大橋さん

投稿内容について、狩野さんと確認しました。
投稿内容に関する指摘は、大橋さんが記載した内容に上書きしています。

また、追加で以下の内容を修正お願いします。

* Issueに投稿する際は、「markdown」で記載することを心がけてください。
  *  投稿するブログも同様です。
* "課題"という言葉は適切でないので、"トレーニング内容"や"施策内容"という表記に修正してください
（課題＝解決すべきお題、施策＝課題を解決するための取り組み）

**Comment by oha-ryo-y2i** [comment]
@nametake55 

遅くなりました。
markdownへの変更ありがとうございます。
"課題"を"トレーニング"に変更しました。
