### ISSUE TITLE
ブログ記事：施策の一週目

### ISSUE THREAD

**Issue by TomoeAizawa** [ykk-yos1982/yayoi#47]
ブログ記事の内容を記載します。
---
初めまして、開発本部のT.Aです。
突然ですが弥生では今年の3月、[フロントエンジニア強化施策](http://tech.yayoi-kk.co.jp/entry/2017/03/01/120000)という取り組みが発足しました。

この3月の取り組み（第一回目）を見ていたメンバーが、自分もやりたい！と参加者を集め、先月から第二回目を開催しています。
私は業務上フロントに関わりないチームなのですが、「やりたい」と周囲に話していた所、参加させていただけることになりました。

というわけで本記事では、第二回フロントエンジニア強化施策の取り組みをババーンとお伝えします！

# メンバー紹介
今回は運営メンバー3名、参加メンバー4名で施策を実施しています。

## 運営メンバー
<details><summary>田中さん</summary>

- フロントシステムチームのリーダー
- 声が大きい（物理）
</details>

<details><summary>K.Kさん</summary>

- マイポータルを作っている
- Markdown記法の存在を私に教えてくれた人
- 質問すると丁寧に教えてもらえる
</details>

<details><summary>S.Uさん</summary>

- SMARTを作っている人
- 第一回目の参加者→今回の運営へ([前回記事](http://tech.yayoi-kk.co.jp/entry/2017/03/06/100000}))
- 弱音を吐くと励ましてもらえる。。。
</details>

## 参加メンバー
  <a name="dksan"></a>
<details><summary>D.Kさん</summary>

  - 入社四年目の先輩
  - オンライン製品作っている人
  - 基本雑だけど本気で困ってると助けてくれる
</details>
  <a name="rosan"></a>
<details><summary>R.Oさん</summary>

  - 入社一年目(中途）の先輩
  - マイポータル作っている人
  - すごくものづくりに対する拘りがある（気がする）
</details>
  <a name="rtsan"></a>
<details><summary>R.Tさん</summary>

  - 入社三年目の先輩
  - 自動テスト作るチームのリーダー
  - 入社から今に至るまでお世話になってます。。。
</details>
T.A(私)

## 自分の話
導入がてら自己紹介を。先に内容が気になる方は[施策の内容](#honpen)へ

### 現在の業務
新卒で入社し、現在二年目です。
[R.Tさん](#rtsan)と同じチームでデスクトップ製品の自動テストを作成・実施しています。
後は新卒の教育チームで後輩の研修や、ふりかえりを実施しています。

### スキル
普段業務で使っているのはC#です。
学生時代フリー配布のテンプレートを編集してサイトを作っていました。
ただ、フロントスキルは「タグとセレクタって何？」「CSSって色変える以外に何ができるの？」というレベルでした。

#### 自分の作りたいもの（Webアプリ）を作るとっかかりを作る
 大学時代、演劇をしていて見るのもやるのも好きでした。
 しかし社会人になってから忙しくなり、公演を見に行くことがめっきり減り…。
 好きな芝居は観たいけど、調べるために色んなサイト回るのは面倒くさい。
 そんな人（自分）のための小劇場・学生演劇に特化した検索アプリを作りたい！
 
 …と思い立ったはいいのですが、Web系の技術は種類が豊富すぎるし、Gitも開発環境も良くわからない。
 ①調べる → ②どの技術から勉強するか決められない → ③一先ず業務でも使うC#の勉強する
 そのループを今年の3月くらいから繰り返していました。

 そんな時に誘っていただいたのが、このフロントエンジニア強化施策です。
 まずフロントエンドの技術をこの強化施策で勉強しよう！
 そこをきっかけにして、他（サーバーサイドとか、フレームワークとか）勉強しよう！
 
 長くなりましたが要するに、この施策をきっかけに自学を進めることを目標にしています。

#### かっこいいサイトを作れるようになる
 私が思うかっこいいサイト例：[弥生30周年記念サイト](https://www.yayoi-kk.co.jp/30th/index.html)
 自分の中で「一から自分でデザインを考えて、調べながらサイトを作れる」ことができたら、フロントエンド少しはできると言っていいんじゃないかなと思っています。
 ただ今まで、ネット上で配布されているテンプレートをいじってサイトを作ってきたため、一からサイトを作ったことがありません。 
 例えば、例に出した弥生のサイトで、メニューのメインの部分はどうやって分けているのか？
 何も見ずに作るのは無理でも、これを使えば実現できそう！と考えられるレベルにはなりたいです。

#### 他チームの方とたくさん話す
 普段はデスクトップ製品の自動テストを作成しているため、オンラインやウェブ製品の開発をしている方と関わりがほとんどありません。それらのチームの方と話して、どんな技術を使って開発しているのか知りたいです。

<a name="honpen"></a>
# 施策の内容
## 使っているツール
- バージョン管理：Git（[SourceTree](https://ja.atlassian.com/software/sourcetree)）
- エディタ　　　：[VisualStudioCode](https://www.microsoft.com/ja-jp/dev/products/code-vs.aspx)

## やり方
- 基本定時後に行う
- ペアプロで実施する
  - 1人がコーディング、もう1人がそれを見てこうした方がいいんじゃないか、とかを話しながら画面を作る
- 成果物の作成が完了したら、レビューを行う

## [最初の1週間でやったこと総まとめ](https://github.com/ykk-yos1982/yayoi/wiki/2nd) 

第一週目は、HTMLとCSSの基礎を学べるような施策を実施しました。
作ったものは全部で3つ。
以下のGitに全てコミットしています。
[成果物置き場](https://github.com/ykk-yos1982/yayoi)

## 施策の内容
1. [レスポンシブ対応画面作成](https://github.com/ykk-yos1982/yayoi/wiki/%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E5%AF%BE%E5%BF%9C%EF%BC%88%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%AA%E3%81%97%EF%BC%89%E7%94%BB%E9%9D%A2%E4%BD%9C%E6%88%90)
 Flexboxを利用して、レスポンシブ対応した画面を作成する
 作成画面：
 ![レスポンシブ](https://raw.githubusercontent.com/ykk-yos1982/yayoi/team4_calender_responsive_aizawa/20170710/team_4/img/res.png)
 ペアプロの担当
    - オペレーター：私
    - ドライバー　：D.Kさん
 一番印象に残っている施策です。
 画面自体はすぐに作成できました。
 意気揚々レビューに出したら、田中さんから一言「Flexboxを何もわかってない！笑」
 この時は、アイテム(1)(2)(3)を一つのdivで囲い、 `display:flex`を当てていました。
 また、 PC用の画面はFlexboxのアイテム(1)を、`width:100%`（横幅いっぱい）にしてアイテム(2)(3)を(1)の下に回り込ませていました。
 しかしそれではFlexboxの良さを全く生かせていないとのこと…。
 頂いた指摘を元にコードを修正。
 ![レスポンシブ](https://raw.githubusercontent.com/ykk-yos1982/yayoi/team4_calender_responsive_aizawa/20170710/team_4/img/res2.png)
 元々上図の①(アイテム(1)(2)(3))しかdivで囲っていなかったのですが、②（アイテム(2)(3))もdivで囲み、それにも`display:flex`を当てました。
 さらに、`flex-direction`プロパティの値を変えることで、widthを指定せず横並びから縦並びに簡単に変えることができました！

2. [セレクタのトレーニング](https://github.com/ykk-yos1982/yayoi/wiki/%E3%82%BB%E3%83%AC%E3%82%AF%E3%82%BF%E3%81%AE%E3%83%88%E3%83%AC%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0)
 HTMLが指定されたデザインになるように、色んなセレクタを使ってスタイルを当てる
 作成画面
 ![CSS](https://raw.githubusercontent.com/ykk-yos1982/yayoi/team4_calender_responsive_aizawa/20170710/team_4/img/css.png)
  ペアプロの担当
    - オペレーター：D.Kさん
    - ドライバー　：私
 [ペアの先輩(D.Kさん)](#dksan)のすごさを実感した施策でした。
 この回は先輩がコーディングをしたのですが、指定されたスタイルをサクサク当てていくので、見ていて楽しかったです。
 ここで「詳細度」というものを教えてもらったのですが、なるほどと、わかった気になってしまい、次の施策で慌てることに…。

3. [mock作成](https://github.com/ykk-yos1982/yayoi/wiki/mock%E4%BD%9C%E6%88%90)
 弥生で実際に使われているボタンやコントロール（共通部品）を利用して、画面を作成する
 作成画面
 ![マイポータル](https://raw.githubusercontent.com/ykk-yos1982/yayoi/team4_calender_responsive_aizawa/20170710/team_4/img/mypotal.png)
  ペアプロの担当
    - オペレーター：私
    - ドライバー　：D.Kさん
 コピーペーストで部品を配置していく簡単（？）なトレーニング。
 なのですが、なかなかお手本のデザインにならず四苦八苦しました。
 上手くいかなかった原因は、
    ① スタイルを当てても、より詳細度の深いものに打ち消されてしまう
    ② コントロールの間に、開発者ツールで見ないとわからない`margin`がある
 セレクタのトレーニングでなんとなくしかセレクタや詳細度を理解しなかったことが仇となりましたが、開発者ツールを駆使し、なんとか完成しました！

# まとめ
### HTMLとCSSについて
- Flexboxを使った画面構成のやり方、レスポンシブ対応した画面の作り方を知った
  - 画面を見たときにどう作ればいいのか、というイメージがつくようになった
- CSSのセレクタの種類と詳細度について知った
  - セレクタ：種類とそれぞれのセレクタの使い方は分かった
  - 詳細度：概念は分かった。詳細度を意識してセレクタを使い分けできているわけではない
- 弥生の共通部品を使ってみた
  - ※弥生標準として使われている「HTML、CSSのテンプレート」らしいです
  - 弥生のフロント開発ではこういうものを使っていると知った

### 他チームの方と話せた
- オンライン製品のソースコードを少しだけ見せてもらえた
  - 使っているライブラリを知った 
- プログラミングする時に便利なショートカットキーや、小技を教えてもらった

サイトのデザインを見て、どう作るのかイメージできるようになれたのは嬉しかったです！
ただ、Flexboxの理解はまだまだ…。
実際にWebサイトを作って、理解を深めていこうと思います。
また、とっかかりができたと自分では思っているので、繁忙期が終わったらフレームワークの勉強に手を出したいな～と思ってます！

# 次の施策は……
![弥生カレンダー](https://raw.githubusercontent.com/ykk-yos1982/yayoi/team4_calender_responsive_aizawa/20170710/team_4/img/calender.jpg)
上の弥生カレンダーをHTMLとCSSで作成中。
Flexboxの新たな発見も有ったりしました。
試行錯誤の詳細は次回の[R.Oさん](#rosan)の記事で！
乞うご期待！

**Comment by oha-ryo-y2i** [comment]
大筋問題ないと思います！
追加で以下の３点についても記載していると良いと思いました。
1.ペアプロで開発している旨と、ペアプロ開発におけるメリット・デメリット
2.担当している通常業務の紹介（本施策で学んでいることと関係ない業務をやっている人が参加している＝会社全体で開発に対する意欲が高い様に見える）
3.参加の経緯をもっと詳細に（誰でも参加できることなどのアピールになるので、他の人の参加の後押しになる）

**Comment by keisukeKarino** [comment]
施策の内容以外を確認しました。
改善案を記載しますので、確認をお願いいたします。

# 自分の話

## スキル
  * 大学時代コピペ&テンプレートでサイト作ってた
    * WordPressかな？使用していた技術を書いてあげる

## フロントのスキルとしてどの程度理解しているのか記載する
  * cssはこの程度理解している、書くことができる 
  * htmlはこの程度理解している、書くことができる
   etc...

## 施策を通じての目標に関して
  * 弥生30周年記念サイトのようなサイトを一から作れるようになる
    * 作れるようになるために、何が足りないと感じていたか（=課題だよね
  * 施策と通じての目標と、近い詳細のありたい姿がまざっていると思うので、  
    まずは今回の施策で何を身につけったいかってところを記載する

# まとめ
* 曖昧な表現は避ける
   * 簡単な枠組みは・・・→なにの？    
   * 基本（詳細度）・・・基本=詳細度みたいになっている
   * 知識の理解はまだまだこれから・・・知識？

* 始める前から、これだけ成長したよ！ってところを伝えてあげる

# 今やっていること
* 弥生のカレンダーを作ってみる
  * どんな、カレンダーなのか読者はわからないから、画像を追加する

**Comment by TomoeAizawa** [comment]
諸々手を付けられておらず申し訳ありません…。
改善案は土日に確認いたします。

**Comment by nametake55** [comment]
以下追加指摘です。
* どんなふうに施策に取り組んでいたか を記載する
（例えばペアプロ：2人で1台のPC使ってやった、1人が手を動かしてもう一人は横からやいやい言ってた、手を動かす人を交互に変えながらやった 等）
* 施策を通じて、期待値に対して結果がどうだったかを書くとよい
（例えば施策を通じての目標：他の人と前より話せるように...の目標は達成した？ をまとめにかく）
* 施策の内容
なんで今回2回目をやることになったのか？
1回目から引き続きでなんとなく始まったわけじゃなく、1回目をみてやりたいと思った人の熱意で開始したのが今回の第2回の開催ポイントだと思っています
勉強会開いてもらって参加しているではなく、フロントエンドを学びたい人たちが集まって施策を実施している
という感じが伝わるように
* 学んだ事
これから記載する箇所だと思いますが、ここは単に学んだ技術を書くのではなく
「施策の中で感じた事」や「悩んだポイント」を具体的に交えて書くとよいと思います
（読み手は、「flexbox」が理解できた とか書いてあったも面白くない）

**Comment by TomoeAizawa** [comment]
記事の作成完了しました。
また、上記のレビュー内容に対応いたしました。

お手数ですが、再度レビューをお願いいたします。

**Comment by nametake55** [comment]
レビュー対応ありがとうございます。
以下、追加の指摘事項です。

* バージョン管理：Git（SourceTree）
→以下、慣れないと理解を誤りやすいので補足です
Git：バージョン管理システム
SourceTree：GitをGUIで使いやすくするためのクライアントツール
※これは補足なので修正は不要です

* "PC用の画面はflexboxのアイテム(1)を、横幅いっぱいにして(2)(3)を回り込ませていたのですが、"
→"横幅いっぱいにして"→widthを100%に指定して のほうが分かりやすいかも

* "頂いた指摘を元にHTMLのdivを再編。"
→divだけを再編したのではなく、flexboxの当て方をどう変えたのか？も記載したほうが分かりやすい
修正前後の実際のソースを添付してはどうでしょうか？

* flexbox
→大文字、小文字の混在あり

* "Flexboxを使ったレイアウトのやり方を知った"
→"Flexboxを使ってレスポンシブデザイン対応の画面の作り方を知った"など、学んで理解できたキーワードは入れたほうが、より施策を通じて「曖昧な理解」→「具体的な理解」に変わったことがアピールできると思います

* "先輩のすごさを実感した施策でした。指定されたスタイルをサクサク当てていくので、見ていて楽しかったです。"
→先輩＝ペアの参加者？先輩がスタイルをあてるのをペアプロで横で見ていた というシチュエーションでしょうか？
"ペアの先輩が"とか一言追加するとわかりやすいかも。

* "弥生の標準部品を使ってみた"
→"標準部品"→"共通部品"
→この部品に関する補足説明をどこかに入れておいたほうがよいと思います

**Comment by TomoeAizawa** [comment]
@nametake55
レビューありがとうございます。対応致しました。
> "頂いた指摘を元にHTMLのdivを再編。"
> →divだけを再編したのではなく、flexboxの当て方をどう変えたのか？も記載したほうが分かりやすい
> 修正前後の実際のソースを添付してはどうでしょうか？

こちらの指摘のソース添付は、どう記載するか悩んでしまったのと、分量が多くなりそうだったため、
文章での説明のみにしています。
ご確認お願いいたします。

**Comment by nametake55** [comment]
「学んだ事」をもう少し具体的に書ければokと思います。
以下修正のポイントです。

## レスポンシブ対応画面作成
* コードの変更前後で何が改善されたのか？
FlexBoxの良さを生かせていないとはどういうこと？
（→この辺floatのように%で指定しなくてよい。縦並び横並びの指定はプロパティで制御できる）

## まとめ
* 画面構成のやり方ってどういうこと？

* CSSセレクタの種類、「詳細度」の何を知った？

* 共通部品
→（読者）なんのこと？

* 基礎わからず
→フロントの技術とはこう！と体系的に理解できていないと、基礎が何かを書くのは難しいかもしれないので、今回できるようになったことを書く

* 業務後に人と一緒にやるので、勉強する時間を取れる
→施策終わったら終わり？

* 今回はD.Kさんとペアで、オンライン製品のソースコードを少しだけ見せてもらえた
→見て得たことは？

* その人がどんな風に開発しているのか、ペアプロで少し知れた
→知ってよかったと思うことがあるのでは？それを書く

**Comment by nametake55** [comment]
## レビュー用備忘
* 伝えたいことは？お土産は？学んだ事は学んだ技術の詳細についてではなく、なんでそれが必要なのか という観点で指摘する

**Comment by nametake55** [comment]
#修正方針すり合わせ用メモ（8/13見直し）

## 施策を通じての目標
* 弥生30周年記念サイト、Webアプリを作る
→それぞれを作れるようになって何を達成したいか、何ができるようになると考えているか 目標を立てた意図を記載する
※一緒に見直しを行う

## 施策の内容
* 3つのトレーニングについて、ペアプロでどちらの立場で作業したか を記載したほうがよい

## レスポンシブ対応画面作成
* コードの変更前後で何が改善されたのか？
改善した内容だけでなく、なぜその改善が必要なのか（改善が必要な理由）を記載してください。
例えば、FlexBoxの良さを生かせていないとはどういうこと？
（FlexBoxの良さ→FlexBoxは縦並び横並びの指定はプロパティで制御できる。floatように、横幅%で折り返し指定しなくてよい。%で折り返し指定するデメリットは？）

## セレクタのトレーニング、mock作成
* それぞれの施策で学んだ事を具体的に記載してください。
  * 2.セレクタのトレーニング
  「詳細度」をどのように理解していた？
  * 3.mock作成
    ＞① スタイルを当てても、より詳細度の深いものに打ち消されてしまう
      詳細度の深いものに打ち消されてしまう→意図したスタイルが当たらない経験をした→
      不要に詳細度が深くなるようなセレクタを記載してはいけない
      という学びはありませんでしたか？
    ＞② コントロールの間に、開発者ツールで見ないとわからないmarginがある
      これは、開発者ツールを駆使して実装する（ソースを解読する）、という点が学びとして記載できるのでは？

## まとめ
* 目標達成度：→削除
* 学んだ事を、今後どう使えるか？を記載する
* 画面構成のやり方ってどういうこと？
* CSSセレクタの種類、「詳細度」の何を知った？
* 共通部品
→（読者）なんのこと？
* 基礎わからず
→目標が全く達成できなかったの？と思われてしまうかもしれません。
フロントの技術を体系的に理解できていないと、基礎が何かを書くのは難しいかもしれないですが、
「基礎はまだ語れないけど、今回の施策でこれはできるようになった」というように、今回の施策でできるようになったことを書くと成長具合が伝わるのでは？
事前に立てた目標に対して、この施策で何ができて、残として何ができていないのかを記載すると良いと思います

* 業務後に人と一緒にやるので、勉強する時間を取れる
→施策終わったら終わってしまう？

* 今回はD.Kさんとペアで、オンライン製品のソースコードを少しだけ見せてもらえた
→見て得たことがあったらそれも書く
見た、という事実だけだと少し弱いかも

* その人がどんな風に開発しているのか、ペアプロで少し知れた
→知ってよかったと思うことがあるのでは？それを書く

**Comment by nametake55** [comment]
### 施策を通じての目標
  - Webアプリを作るためのとっかかりを作る
    - HTMLとCSSの基礎が全くないので、施策を通じて学びたい
      - そもそも何が基礎なのか知りたい

→Webアプリの具体的な情報を記載する（小劇場）

  - [弥生30周年記念サイト](https://www.yayoi-kk.co.jp/30th/index.html)のようなサイトを一から作るには何が必要か知る
→
1. フロントの導入としてまずはCSSやHTMLを理解したい
1. 具体的に、今回の施策で習得したいと思っていた事
  * フロントを構成する技術を知りたい
  * 環境構築ができるようになりたい
  * チーム開発でソース管理する方法がわかっていない
  * 開発ツールを利用して開発したい（ずっとテキストエディタで開発していた）

    - やりたいけど勉強を後回しにしている、今の状況を変えたい
→
* 業務で利用しているC#の勉強を優先させてしまう
* ずっとやりたいと思っているフロントの技術を勉強するきっかけ
（きっかけを得て、今後の勉強の入口となることを期待）
* 短期間でレベルアップしている姿をみていた

  - 他チームの方とたくさん話す
    - 他チームがどんな風に開発しているのか知りたい
→普段の業務では、自分のチームのことしか見られていない。（他チームとのかかわりがない）


## 学んだこと
* FlexBoxが分かった
→
画面を見たときにどう作ればいいのか、というイメージがつくようになった。
例を出すなら、目標にあった「弥生30周年記念サイト 」を出す

* CSSセレクタと詳細度の理解
→
セレクタ：種類とそれぞれのセレクタの使い方は分かった。
詳細度：概念は分かった。詳細度を意識してセレクタを使い分けできているわけではない。

実際に実装するときの使い分けまでは理解できていない。（どういったケースで〇〇セレクタを使うべきか、こういうケースでは、〇〇セレクタはつかうべきではない）
トレーニングの中では、HTMLにもともとセレクタが指定されていたので、自分で適切なセレクタを使えるレベルまでは理解できていない。

* 共通部品
※弥生標準として使われている「HTML、CSSのテンプレート」
→会社のことを知った。コピペで簡単に画面が作れる

* 今回はD.Kさんとペアで、オンライン製品のソースコードを少しだけ見せてもらえた
→使っているライブラリなどを知った

* Gitからソースをローカルに展開する方法が分かった
（まだGitの運用については理解しきれていない）

* 最終的にこのサイトが作れそう！のようなまとめとする


→結びとしては、
目標「基礎を学んで何かをつくりたい」が、
施策を通して、「ここまではできるようになった」

**Comment by nametake55** [comment]
## 8/17メモ
* そんな時に誘っていただいたのが
→知ったのが のほうがよい
（やりたい人たちが集まった という上の記述とずれてしまう）

* 自学
→自主学習

* Flexbox
→第2回の記事と合わせたいので、小文字flexboxに修正

* ボタンやコントロール（共通部品）
→フロント側だとあんまり「コントロール」という呼び方しない
.NET フレームワークだと、サーバーサイドのコントローラーの意味で使うよう？【要確認】
（追記）「UIの共通部品」と記載するとわかりやすいと思います。

**Comment by TomoeAizawa** [comment]
「 初めてのフロントエンド」というタイトルで、はてなブログに下書きを保存しました。
ご確認をお願いいたします。

**Comment by TomoeAizawa** [comment]
タイトル：初めてのフロントエンド

初めまして、開発本部のT.Aです。
突然ですが弥生では今年の3月、[フロントエンジニア強化施策](http://tech.yayoi-kk.co.jp/entry/2017/03/01/120000)という取り組みが発足しました。

この3月の取り組み（第一回目）を見ていたメンバーが、自分もやりたい！と参加者を集め、先月から第二回目を開催しています。
私は業務上フロントに関わりないチームなのですが、「やりたい」と周囲に話していた所、参加させていただけることになりました。

というわけで本記事では、第二回フロントエンジニア強化施策の取り組みをババーンとお伝えします！


# メンバー紹介
今回は運営メンバー3名、参加メンバー4名で施策を実施しています。

## 運営メンバー
<details><summary>田中さん</summary>

- フロントシステムチームのリーダー
- 声が大きい（物理）
</details>

<details><summary>K.Kさん</summary>

- マイポータルを作っている
- Markdown記法の存在を私に教えてくれた人
- 質問すると丁寧に教えてもらえる
</details>

<details><summary>S.Uさん</summary>

- SMARTを作っている人
- 第一回目の参加者→今回の運営へ([前回記事](http://tech.yayoi-kk.co.jp/entry/2017/03/06/100000}))
- 弱音を吐くと励ましてもらえる。。。
</details>

## 参加メンバー
  <a name="dksan"></a>
<details><summary>D.Kさん</summary>

  - 入社四年目の先輩
  - オンライン製品作っている人
  - 基本雑だけど本気で困ってると助けてくれる
</details>
  <a name="rosan"></a>
<details><summary>R.Oさん</summary>

  - 入社一年目(中途）の先輩
  - マイポータル作っている人
  - すごくものづくりに対する拘りがある（気がする）
</details>
  <a name="rtsan"></a>
<details><summary>R.Tさん</summary>

  - 入社三年目の先輩
  - 自動テスト作るチームのリーダー
  - 入社から今に至るまでお世話になってます。。。
</details>
T.A(私)

## 自分の話
導入がてら自己紹介を。先に内容が気になる方は[施策の内容](#honpen)へ

### 現在の業務
新卒で入社し、現在二年目です。
[R.Tさん](#rtsan)と同じチームでデスクトップ製品の自動テストを作成・実施しています。
後は新卒の教育チームで後輩の研修や、ふりかえりを実施しています。

### スキル
普段業務で使っているのはC#です。
学生時代フリー配布のテンプレートを編集してサイトを作っていました。
ただ、フロントスキルは「タグとセレクタって何？」「CSSって色変える以外に何ができるの？」というレベルでした。

### 施策を通じての目標
#### 自分の作りたいもの（Webアプリ）を作るとっかかりを作る
 大学時代、演劇をしていて見るのもやるのも好きでした。
 しかし社会人になってから忙しくなり、公演を見に行くことがめっきり減り…。
 好きな芝居は観たいけど、調べるために色んなサイト回るのは面倒くさい。
 そんな人（自分）のための小劇場・学生演劇に特化した検索アプリを作りたい！
 
 …と思い立ったはいいのですが、Web系の技術は種類が豊富すぎるし、Gitも開発環境も良くわからない。
 ①調べる → ②どの技術から勉強するか決められない → ③一先ず業務でも使うC#の勉強する
 そのループを今年の3月くらいから繰り返していました。

 そんな時に知ったのが、このフロントエンジニア強化施策です。
 まずフロントエンドの技術をこの強化施策で勉強しよう！
 そこをきっかけにして、他（サーバーサイドとか、フレームワークとか）勉強しよう！
 
 長くなりましたが要するに、この施策をきっかけに自主学習を進めることを目標にしています。

#### かっこいいサイトを作れるようになる
 私が思うかっこいいサイト例：[弥生30周年記念サイト](https://www.yayoi-kk.co.jp/30th/index.html)
 自分の中で「一から自分でデザインを考えて、調べながらサイトを作れる」ことができたら、フロントエンド少しはできると言っていいんじゃないかなと思っています。
 ただ今まで、ネット上で配布されているテンプレートをいじってサイトを作ってきたため、一からサイトを作ったことがありません。 
 例えば、例に出した弥生のサイトで、メニューのメインの部分はどうやって分けているのか？
 何も見ずに作るのは無理でも、これを使えば実現できそう！と考えられるレベルにはなりたいです。

#### 他チームの方とたくさん話す
 普段はデスクトップ製品の自動テストを作成しているため、オンラインやウェブ製品の開発をしている方と関わりがほとんどありません。それらのチームの方と話して、どんな技術を使って開発しているのか知りたいです。

<a name="honpen"></a>
## 施策の内容
### 使っているツール
- バージョン管理：Git（[SourceTree](https://ja.atlassian.com/software/sourcetree)）
- エディタ　　　：[VisualStudioCode](https://www.microsoft.com/ja-jp/dev/products/code-vs.aspx)

### やり方
- 基本定時後に行う
- ペアプロで実施する
  - 1人がコーディング、もう1人がそれを見てこうした方がいいんじゃないか、とかを話しながら画面を作る
- 成果物の作成が完了したら、レビューを行う

### [最初の1週間でやったこと総まとめ](https://github.com/ykk-yos1982/yayoi/wiki/2nd) 

第一週目は、HTMLとCSSの基礎を学べるような施策を実施しました。
作ったものは全部で3つ。
以下のGitに全てコミットしています。
[成果物置き場](https://github.com/ykk-yos1982/yayoi)

1. [レスポンシブ対応画面作成](https://github.com/ykk-yos1982/yayoi/wiki/%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B7%E3%83%96%E5%AF%BE%E5%BF%9C%EF%BC%88%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%AA%E3%81%97%EF%BC%89%E7%94%BB%E9%9D%A2%E4%BD%9C%E6%88%90)
 flexboxを利用して、レスポンシブ対応した画面を作成する  
 作成画面
 [f:id:tomoe_aizawa:20170817085447p:plain]
 ペアプロの担当：オペレーター⇒私、ドライバー⇒D.Kさん  
 一番印象に残っている施策です。
 画面自体はすぐに作成できました。
 意気揚々レビューに出したら、田中さんから一言「flexboxを何もわかってない！笑」
 この時は、アイテム(1)(2)(3)を一つのdivで囲い、 `display:flex`を当てていました。
 また、 PC用の画面はflexboxのアイテム(1)を、`width:100%`（横幅いっぱい）にしてアイテム(2)(3)を(1)の下に回り込ませていました。
 しかしそれではflexboxの良さを全く生かせていないとのこと…。
 頂いた指摘を元にコードを修正。
 [f:id:tomoe_aizawa:20170817085626p:plain]
 元々上図の①(アイテム(1)(2)(3))しかdivで囲っていなかったのですが、②（アイテム(2)(3))もdivで囲み、それにも`display:flex`を当てました。
 さらに、`flex-direction`プロパティの値を変えることで、widthを指定せず横並びから縦並びに簡単に変えることができました！

2. [セレクタのトレーニング](https://github.com/ykk-yos1982/yayoi/wiki/%E3%82%BB%E3%83%AC%E3%82%AF%E3%82%BF%E3%81%AE%E3%83%88%E3%83%AC%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0)
 HTMLが指定されたデザインになるように、色んなセレクタを使ってスタイルを当てる  
 作成画面
 [f:id:tomoe_aizawa:20170817085607p:plain]
 ペアプロの担当：オペレーターD.Kさん⇒、ドライバー⇒私  
 [ペアの先輩(D.Kさん)](#dksan)のすごさを実感した施策でした。
 この回は先輩がコーディングをしたのですが、指定されたスタイルをサクサク当てていくので、見ていて楽しかったです。
 ここで「詳細度」というものを教えてもらったのですが、なるほどと、わかった気になってしまい、次の施策で慌てることに…。

3. [mock作成](https://github.com/ykk-yos1982/yayoi/wiki/mock%E4%BD%9C%E6%88%90)
 弥生で実際に使われているボタンなどを利用して、画面を作成する  
 作成画面
 [f:id:tomoe_aizawa:20170817085642p:plain]
 ペアプロの担当：オペレーター⇒私、ドライバー⇒D.Kさん  
 コピーペーストで部品を配置していく簡単（？）なトレーニング。
 なのですが、なかなかお手本のデザインにならず四苦八苦しました。
 上手くいかなかった原因は、
    ① スタイルを当てても、より詳細度の深いものに打ち消されてしまう
    ② コントロールの間に、開発者ツールで見ないとわからない`margin`がある
 セレクタのトレーニングでなんとなくしかセレクタや詳細度を理解しなかったことが仇となりましたが、開発者ツールを駆使し、なんとか完成しました！


# まとめ
## 施策を通じて学んだこと
### HTMLとCSSについて
- flexboxを使った画面構成のやり方、レスポンシブ対応した画面の作り方を知った
  - 画面を見たときにどう作ればいいのか、というイメージがつくようになった
- CSSのセレクタの種類と詳細度について知った
  - セレクタ：種類とそれぞれのセレクタの使い方は分かった
  - 詳細度：概念は分かった。詳細度を意識してセレクタを使い分けできているわけではない
- 弥生の共通部品を使ってみた
  - ※弥生標準として使われている「HTML、CSSのテンプレート」らしいです
  - 弥生のフロント開発ではこういうものを使っていると知った

### 他チームの方と話せた
- オンライン製品のソースコードを少しだけ見せてもらえた
  - 使っているライブラリを知った 
- プログラミングする時に便利なショートカットキーや、小技を教えてもらった

サイトのデザインを見て、どう作るのかイメージできるようになれたのは嬉しかったです！
ただ、flexboxの理解はまだまだ…。
実際にWebサイトを作って、理解を深めていこうと思います。
また、とっかかりができたと自分では思っているので、繁忙期が終わったらフレームワークの勉強に手を出したいな～と思ってます！


# 次の施策は……
[f:id:tomoe_aizawa:20170817085701j:plain]
上の弥生カレンダーをHTMLとCSSで作成中。
flexboxの新たな発見も有ったりしました。
試行錯誤の詳細は次回の[R.Oさん](#rosan)の記事で！
乞うご期待！

**Comment by nametake55** [comment]
* ボタンやコントロール（共通部品）
以下追記の内容の反映をお願いします。
→（追記）「UIの共通部品」と記載するとわかりやすいと思います。

~~~
【修正前】
弥生で実際に使われているボタンなどを利用して、画面を作成する
【修正後】
弥生で実際に使われているボタンなどの「UIの共通部品」などを利用して、画面を作成する
~~~

* ② コントロールの間に、開発者ツールで見ないとわからないmarginがある
→ここの"コントロール"の記載も同様に修正お願いします

**Comment by TomoeAizawa** [comment]
反映漏れ申し訳ないです…。
はてなブログの下書きで、該当箇所を修正しました。
