### ISSUE TITLE
ブログ記事：カレンダートレーニング（途中経過）

### ISSUE THREAD

**Issue by oha-ryo-y2i** [ykk-yos1982/yayoi#48]
@nametake55 @ykk-yos1982  @keisukeKarino 
以下の内容でブログを投稿する予定です。
ご確認お願い致します。
---

はじめまして、エンジニアのR.Oです！  
前回の記事でT.Aさんが紹介したトレーニングに続き、「カレンダー作成トレーニング」に挑戦中なのでその途中経過を報告します。

## 自己紹介

まずは、自己紹介をさせていただきます。
私は今年の春に弥生に中途入社し、現在はWebサービスの開発チームでフロントエンドとサーバーサイドの開発を担当しています。
プライベートではAWSを使ったWebチャットアプリケーションの開発に挑戦中です。

趣味は飲酒とボルダリングです。
ボルダリングは昔に少しやっていて、二ヶ月前に再開しました。最近は6級であればほぼ一発で登れるようになりました。  
今年中に4級を安定して登れるようになることが目標です。
因みに、ボルダリングで何が一番楽しいかというと、_難しい壁になんとか登れた時!!_  
ではなくボルダリング終わりに飲みに行ってお酒を飲むことです。

## 強化施策に参加したきっかけ

弥生に入社する前は、サーバーサイドの開発経験がメインだったので、フロントエンドの開発も行うチームに配属されたことに不安を抱いていました。
また、前述の通り、Webのチャットアプリケーションを作成したいのにフロントエンドの知識がなくて困っていました。  

そんな時に本施策の第一弾が社内で行われているのを目にし、渡りに船と第二弾のメンバーとして手を上げたことが参加のきっかけです。    

## 強化施策を通して身につけたいもの  

フロントエンド開発における以下のスキルを身に着けたいと考えています。
1. HTMLとCSSの基礎（HTMLタグの使い方やCSSのセレクタなど）
1. flexbox
1. BEM(MindBEMding)
1. Sass

1.と2.に関しては前回のトレーニングで学習できたので、今回のトレーニングでは3.のBEMを身に着けたいと考えています。  

BEMはクラスの命名規則の一つです。  
今まではクラスに対して、フィーリングで名前をつけていたので、後で見返した時に「これってなんのために作った要素だっけ？」となることがありました。  
BEMの命名規則をうまく活用することができればそういった問題を解決できるらしいです。また、チームで作業する際にクラス名のブレを防いだり、拡張性の高いコンポーネント作成を行えるようにもなるらしいので、是非身に着けたいです。

因みに、クラスの命名規則の中ではデファクトスタンダード扱いされているらしく、CSSフレームワークで人気のBootstrapでも採用されています。

BEMの詳細については以下の記事などを参考にしてください。  
http://qiita.com/kitaro729/items/3189ded5647475bc2ae7  

### 作成するもの

卓上カレンダーをHTMLとCSSで再現します。

以下の画像が実際の卓上カレンダーの写真です。  

<カレンダー.jpg>

### 実施方針

- ヒントや正解となるコードはなし  
- ペアプログラミングで作成する  
- クラスはBEM（MindBEMding）に則って命名する（※私のチームのみ）

### HTMLの作成段階で悩む
「前回のトレーニングで学んだCSSセレクタやCSSプロパティの知識を総動員してサクッと作成するぞ！」と意気込んで着手したのですが、HTMLの作成段階で悩んでしまいました。  
なぜならカレンダーには枠、日付、六曜、祝日などの多くの種類と要素があります。

![default](https://user-images.githubusercontent.com/26620507/29313268-18727bd6-81f4-11e7-9261-303062958c1e.jpg)

また、種類が沢山ある＝要素に設定するクラスが多いので、命名するのも一苦労です。  

### CSSは順調！・・・かと思いきや！？
ペアとあれやこれやと相談しながらHTMLが書けたので、CSSでスタイルを適用していきます。
カレンダーの様なグリッドスタイルは前回のトレーニングで身につけた（と思い込んでいる）flexboxにとってはお手の物です。  
スタイルが適用され、真っ白だったページが順調にカレンダーになっていきます。  

と思いきや、問題発生です。

カレンダーの左下を再現しようとするとレイアウトが崩れてしまいます。 

![2017-08-09_200330](https://user-images.githubusercontent.com/26620507/29118657-d879a960-7d3d-11e7-82c0-7416c8ae3d28.jpg)

原因は、HTMLの構造にありました。

### 修正前のHTMLとCSS  

左下の日付の枠のHTML

~~~HTML
<div class="halfbox__container boxcommon sun">
    <div class="halfbox">
        <div class="day"></div>
        <div class="rokuyou"></div>
    </div>
</div>
~~~

それ以外の日付の枠のHTML

~~~HTML
<div class="week__body__box boxcommon sun">
    <div class="day"></div>
    <div class="rokuyou"></div>
</div>
~~~

CSS

~~~HTML
.halfbox__container {
    padding:5px
}
.week__body__box {
    padding:5px
}
~~~

HTMLのタグ構造の深さが異なります。

### 修正後のHTMLとCSS   

左下の日付の枠のHTML
~~~HTML
<div class="halfbox__container boxcommon sun">
    <div class="halfbox">
        <div class="day"></div>
        <div class="rokuyou"></div>
    </div>
</div>
~~~

それ以外の日付の枠のHTML

~~~HTML
<div class="week__body__box boxcommon sun">
    <div class="week__body__box__child">
        <div class="day"></div>
        <div class="rokuyou"></div>
    </div>
</div>
~~~

CSS

~~~HTML
.halfbox {
    padding:5px
}
.week__body__box__child {
    padding:5px
}
~~~

HTMLの構造の深さを統一し、CSSでスタイルを適用した結果うまくいきました。

### ひとまず完成

スタイルの設定も完了し、本物のカレンダーの見た目を再現できました。

スクリーンショット
![default](https://user-images.githubusercontent.com/26620507/29023839-5acf73d0-7baa-11e7-9635-2db506c3f988.jpg)

ソースコード  
<https://github.com/ykk-yos1982/yayoi/tree/team4_calender_complete(not_responsive)>  

コードレビューについては次回の記事で報告します。

## 学んだこと
まだコードレビューが完了していませんが、今回のトレーニングでは以下のことを学びました。  

### 事前のHTML設計が予期せぬレイアウト崩れを防ぐ
カレンダーのレイアウト崩れが発生した時に、CSSを色々変えてもうまくいかなかった原因は、CSSを適用するHTMLの構造にそもそも問題があるからでした。
歪んだ骨組みに、無理に肉付けをしてもうまくいくわけがないですね・・・。  

その結果として、HTML作成→CSS適用→HTML修正→CSS適用という手戻りが発生してしまいました。

この失敗を学びとして、今後は以下の流れで画面レイアウトを作成しようと思います。

※カレンダー作成を例にしています。
1. *作るレイアウトの構成を理解する*
  例：「枠が沢山並んでいて、それぞれの枠の中に日付、祝日、六曜が存在する。祝日は日付と横並びだが、六曜は日付と縦並びになっている」
1. *理解した構成に合わせてHTMLを設計・作成する*
  例：「枠となる要素を沢山作り、それぞれの枠の中に日付、祝日、六曜となる要素を作る。まずは日付と祝日の要素が横並びになる要素を作り、その要素と六曜が縦並びになる要素を作る」
1. *HTMLに合わせてCSSを適用する*
  例：「枠要素にはborderプロパティを適用、日付と祝日の要素が入っている要素にはflexプロパティのrowを適用、日付＋祝日の要素と六曜の要素が入っている要素にはflexプロパティのcolumnを適用」

上記の流れに則って作成すれば、今回のトレーニング実施で発生したような手戻りを防ぐことができるはずです。

また、今回の経験で、設計という工程がHTML作成においても重要だと気付くことができした。

## 次回予告

次回は、カレンダートレーニングの実施完了報告として、コードレビューの結果とレビュー指摘への対応、カレンダー作成トレーニングを通して学んだことを報告する予定です。  

引き続きよろしくお願いします！

**Comment by nametake55** [comment]
以下指摘事項です。
## 自己紹介とフロントエンジニア強化施策に参加したきっかけ
* フロントエンドの技術の何が必要と感じていたか、を少し具体的に書くとよいと思う
（この施策の中でどういった技術を習得したい、習得できると期待して取り組んだか）
## トレーニング概要
* "内容としては弥生が作成してお客様や社内に配布している卓上カレンダーをHTMLで再現するというもの。"
→卓上カレンダー で伝わるかも。または実際のカレンダーの写真を載せるとか
→HTMLだけで再現するという課題ではなかったと思います。細かいですが誤解がないよう厳密に
## CSSは順調！・・・かと思いきや！？
* "HTMLやCSSに限らず、設計の重要さを改めて実感しました。"
→いい学びだと思うので、うまくいかなかった具体例を出したほうが、読者も「なるほど」と納得できると思います
"HTMLの構造を変えるしかないという結論になりました。"
→ここもそうですが、なぜそうなった？何が悪かった？が知りたい
今回の記事で書きたい要点は、「施策の中で何に躓いているのか」という点だったとおもうので、その躓きポイントを1つでもよいので具体的に書くといいと思います。
## その他全体的に
* "CSS"の小文字、大文字の混在は統一する
* CSSのデザイン設定→CSSでスタイル適用

**Comment by oha-ryo-y2i** [comment]
@nametake55 
指摘に対応しました。お手数ですが、再度ご確認お願いします。

**Comment by nametake55** [comment]
レビュー対応ありがとうございます。
以下、追加の指摘事項です。

* "自分たちで命名したID名/クラス名が分かりにくく関係ないクラスに適用したりはしながらも、真っ白だったページが順調にカレンダーになっていきます！"
→ "関係ないクラスに適用"のイメージが少しわかなかったです。似たようなクラス名を複数設定してしまったため、誤ってスタイルを当ててしまった？

* 「CSSは順調！・・・かと思いきや！？」の"修正前"、"修正後"
→ markdownで太文字にする等したほうが読みやすいと思いました

* ソースを添付した箇所のmarkdown
→ ~~~html  [内容]  ~~~  で、記載してみてください

* "HTML設計時に時間をかけたはずですが、やはり修正が必要になってしまったので設計の重要さを痛感しました。"
→ 「設計」と一言で言ってしまうと少し曖昧さが出るので、"階層を意識したHTMLの記述"などと具体的に記載するほうがよいと思います

* "スタイルの設定も完了し、本物のカレンダーを正しく再現できました。"
→ "正しく"が曖昧なので、"カレンダーを現物の見た目通りに"などと記載するほうがよいと思います

* "HTML設計を事前にしっかりとしておけば手戻りを減らすことができる"
→ "しっかりと"が曖昧なので、今回の施策で学んだ"しっかり"の内容を具体的な言葉で記載してみてください。

* 画像ファイルについて
→ .jpgのファイルを添付したイメージを確認して最終レビューしたいため、修正後のレビューはjpgファイルも当て込んだ状態でレビュー依頼をお願いします

**Comment by oha-ryo-y2i** [comment]
@nametake55 
レビューありがとうございます。指摘対応しました。

---

はじめまして、エンジニアのR.Oです！  
前回の記事でT.Aさんが紹介したトレーニングに続き、「カレンダー作成トレーニング」に挑戦中なのでその途中経過を報告します。

## 自己紹介

まずは自己紹介をさせていただきます。
私は今年の春に弥生に中途入社し、現在はWebサービスの開発チームでフロントエンドとサーバーサイドの開発を担当しています。
プライベートではAWSを使ったWebチャットアプリケーションの開発に挑戦中です。

## 強化施策に参加したきっかけ

弥生に入社する前はサーバーサイドの開発経験がメインだったので、フロントエンドの開発も行うチームに配属されたことに不安を抱いていました。
具体的には、HTMLやCSSでのUI開発において「このデザインを実現するためにどのCSSプロパティを使うべきか」、「どのようなHTML構造にすれば高い拡張性やメンテナンス性を実現できるのか」といった知識があまりなかったのです。

そんな不安を抱いていた時に本施策の第一弾が社内で行われているのを目にし、渡りに船と第二弾のメンバーとして手を上げたことが参加のきっかけです。    

## トレーニングの概要
### 作成するもの

今回は卓上カレンダーをHTMLとCSSで再現します。

以下の画像が実際の卓上カレンダーの写真です。  

<カレンダー.jpg>

### 実施方針

- ヒントやサンプルはなし  
- ペアプログラミングで作成  
- 作成後、コードレビューを実施する  

## 実施レポート

### HTMLの作成段階で悩む
「学んだCSSセレクタやCSSプロパティの知識を総動員してサクッと作成するぞ！」と意気込んで着手したのですが、HTMLの作成段階で悩んでしまいました。  
なぜなら対象のカレンダーは枠、日付、六曜、祝日など沢山の要素があるので何も考えずにHTMLを書いてしまうと以下の問題が発生する恐れがあります。

- HTMLの構造が複雑になる
- CSSのスタイル適用が思うようにいかない

また、要素が沢山ある＝HTMLタグも沢山必要なのでCSSセレクタ用のID名/クラス名もその数だけ設定しなければなりません。スタイル適用の際に混乱しないように分かりやすい名前をつけるべきですが、これもなかなか難しいです。

ペアとあれやこれやと相談しながらHTMLを書いていきます。

### CSSは順調！・・・かと思いきや！？
HTMLが書けたので、CSSでスタイルを適用していきます。
カレンダーの様なグリッドスタイルは前回のトレーニングで身につけた（と思い込んでいる）flexboxにとってはお手の物です。  
途中、自分たちで命名したID名/クラス名がわかりにくく  
~~~HTML
<div class="box_common">
~~~
別のクラスに適用すべきプロパティを適用するという簡単なミスはありましたが、真っ白だったページが順調にカレンダーになっていきます！  

と思いきや、大きな壁にぶち当たってしまいました。

カレンダーの左下を再現しようとするとレイアウトが崩れてしまいます。 

#### カレンダーの左下
![default](https://user-images.githubusercontent.com/26620507/29023883-8b02dbc8-7baa-11e7-8c6e-40b77241c49d.jpg)

#### レイアウトが崩れてしまいます
![default](https://user-images.githubusercontent.com/26620507/29023889-926b5a84-7baa-11e7-84ac-9d183d70e18f.jpg)

CSSプロパティを色々試してみましたがうまくいかないので、HTMLを修正した結果うまくいきました。

### 修正前  

左下の日付の枠

~~~HTML
<div class="halfbox__container boxcommon sun">
    <div class="halfbox">
        <div class="day"></div>
        <div class="rokuyou"></div>
    </div>
</div>
~~~

それ以外の日付の枠

~~~HTML
<div class="week__body__box boxcommon sun">
    <div class="day"></div>
    <div class="rokuyou"></div>
</div>
~~~

タグ構造の深さが異なります。

### 修正後  

左下
~~~HTML
<div class="halfbox__container boxcommon sun">
    <div class="halfbox">
        <div class="day"></div>
        <div class="rokuyou"></div>
    </div>
</div>
~~~

それ以外

~~~HTML
<div class="week__body__box boxcommon sun">
    <div class="week__body__box__child">
        <div class="day"></div>
        <div class="rokuyou"></div>
    </div>
</div>
~~~

タグ構造の深さを統一しました。

HTML設計時に時間をかけたはずですが、やはり修正が必要になってしまいました。

### ひとまず完成

スタイルの設定も完了し、本物のカレンダーの見た目を再現できました。

スクリーンショット
![default](https://user-images.githubusercontent.com/26620507/29023839-5acf73d0-7baa-11e7-9635-2db506c3f988.jpg)

ソースコード  
<https://github.com/ykk-yos1982/yayoi/tree/team4_calender_complete(not_responsive)>  

コードレビューについては次回の記事で報告します。

## 学んだこと
まだコードレビューが完了していませんが、現時点で学んだことは以下のとおりです。

- 事前にCSSの適用を考慮したHTML設計・作成をすればHTML修正の手戻りを減らすことができる
- CSSの命名規則をわかりやすくすることでスタイルの適用ミスを減らすことができる
- CSSのfont-familyプロパティの設定方法

## 次回予告

次回はカレンダートレーニングの実施完了報告として、コードレビューの結果とレビュー指摘への対応、カレンダー作成トレーニングを通して学んだことを報告する予定です。  

引き続きよろしくお願い致します！

**Comment by nametake55** [comment]
＞大橋さん
指摘の修正ありがとうございます。
流れがよく、読みやすかったです。

1点だけ指摘です。
* 学んだこと>BEMの命名規則 について
BEMの命名規則がどういう風に理解できたのか、を記載するとさらに具体性が増すと思います。
（今回のカレンダーの施策の目的として「BEM」を挙げているので、学んだ事についてもそこが書けるとよいと思います。）

→ブログに（仮保存状態）で移植をお願いします。
そちらで最終確認後、投稿 の流れにしたいと思います。

**Comment by oha-ryo-y2i** [comment]
@ykk-yos1982 @keisukeKarino @nametake55 
週末に以下の修正を行う予定です。

- 「 強化施策を通して身につけたいもの」で記載されているBEMを知らない読み手も多いはずなので、BEMの概要となぜ身につけたいかを追記する。
- 「強化施策に参加したきっかけ」を削りすぎてしまい、参加への熱意が弱く見えるようになってしまったので、記載し直す。
- 「学んだこと」に学んだことを今後どう活かしていくかがないので、読み手にとっては学ぶことが少ない記事になってしまっているので修正する。
- 「学んだこと」の「タグ構造」が正しい言葉ではないので修正する。
- 読み手によって解釈が変わる可能性のある箇所があるので、一意性を持った記載内容に修正する。
- 躓きの原因であるHTMLの解説が読み手にとってイメージしにくいので、わかりやすい画像などを追加する。

**Comment by nametake55** [comment]
修正方針ありがとうございます。確認します。

**Comment by nametake55** [comment]
#修正方針すり合わせ用メモ（8/13見直し）

* 「 強化施策を通して身につけたいもの」で記載されているBEMを知らない読み手も多いはずなので、BEMの概要となぜ身につけたいかを追記する。
→「なぜ身につけたいか」に重点を置いて記載する事
なぜ数あるフロントの技術の中からBEMを学びたいと思ったか、なぜBEMが必要だと考えているのか、BEMを身につけるとHTMLとCSSを記載する上で何が実現できるのか？
この辺りまで書けるといいと思います。
（BEMという命名規則があるけど、なぜCSSで命名規則が必要なのか理解できていなかったから、施策で実際に使って見たかったいう事であれば、そのような理由を書いてもいいと思います）

* 「学んだこと」に学んだことを今後どう活かしていくかがないので、読み手にとっては学ぶことが少ない記事になってしまっているので修正する。
→BEMについては、実施レポートで具体的に触れていないので、唐突感が出ないように少し丁寧な記載が必要
例えば、「設定した要素の意味やが明確になり、可読性が増す。」とはどういうことか
当ブログの読者を想定していたと思うので、その読者が理解できる言葉と内容で書く事を意識すると良いと思います。

* 「学んだこと」の「タグ構造」が正しい言葉ではないので修正する。
→「タグ構造」の文言を修正する事　が本質的な指摘内容ではなかったと思うので、その点を注意して修正すると良いと思います。
（「タグ構造を意識しながらHTML作成する」とはどういう事か、が施策を実施していない読者に伝わればok）

* 修正の方針としては、以下の点抑えられれば良いと思います
  1. 学んだ事を具体的に、読者に伝わるように記載する
  1. このブログで書きたいことが上から下まで読んだ時に伝わるか？
  1. 各章の内容が繋がっているか
  1. 事前に立てた目標に対して、この施策で何ができて、残として何ができていないのかを記載する
  1. 学んだ事を、今後どう使えるか？を記載する

**Comment by oha-ryo-y2i** [comment]
@nametake55 @ykk-yos1982  @keisukeKarino 
レビュー指摘に対応しました。お手数ですが、再度ご確認お願い致します。

**Comment by nametake55** [comment]
## 強化施策を通して身につけたいもの
* メンテナンス性の高いコンポーネントを作成できるようになるらしいので
→BEMのメリットとして理解していることと、書き方が合っているか確認したいので、後で口頭でここの内容を聞かせてもらえますか？
**→こちら口頭で内容確認できたため、修正は不要です**

## CSSは順調！・・・かと思いきや！？
* HTML構造を直して解決と記載してありますが、「CSSで何とかしようと思っていたけど、HTMLの構造から見直して解決した」という内容に見て取れました。
**→"HTMLの構造の深さを統一し、CSSを修正した結果うまくいきました。"の記載があったため、修正不要です**

## 学んだこと
* クラスの命名時にBEMを使ったことによって、HTML構造がひと目でわかるようになり、
→トレーニングの内容を見ると、「BEMの命名規則が万能だった」わけではなく、BEMの命名規則に従ってクラス名をつけるために、HTMLを構造化（親要素と子要素の関係性を意識した、類似の要素を同階層に揃えた）した
という風に理解しましたが、どうでしょうか？
その場合は、"クラスの命名時にBEMを使ったことによって、XXXXを意識してクラス名をつけたので、HTML構造がひと目でわかるようになった"と記載すると
BEMの恩恵をどう受けたのか、が記載できると思います。
**→こちら修正をお願いします。**

**Comment by oha-ryo-y2i** [comment]
@nametake55 @ykk-yos1982 @keisukeKarino
レビュー指摘に対応しました。お手数ですが、再度ご確認お願い致します。

**Comment by nametake55** [comment]
## 8/17 ポイント
* BEMの「学んだこと」は次回にまとめて記載する
* レイアウトを決めるのはCSSだけではない
→「レイアウト崩れはCSSだけで直すべからず」的なニュアンスにする
（"レイアウト"は、「配置、設計」などの意味が強いため、もともとレイアウトを決めているのはHTMLでは？という印象を受ける）

**Comment by keisukeKarino** [comment]
BEMの記載は次回のブログに記載してください。

まとめは、以下のような構成で記載してみてください。

カレンダーのレイアウト崩れが発生した時、最初はCSSの設定ばかりを変えていましたが、うまくいきませんでした

同じ見た目のレイアウトに関しては、同一のHTML階層にすることで
よきせぬスタイルの適用を防ぐことができます。

下記、手戻りの少ないHTMLを作成できることがわかりました。

①Html構造を設計する
　　同一の見た目のデザインのパーツは、同一の構造で作成する
　例）たとえば今回でいうと・・・

②Html構造に合わせて、CSSを適用する
　例）たとえば今回でいうと・・・

①②を平行してやってしまうと、どこかでつじつまがあわなくなるよね

今後はCSSで無理やりレイアウト崩れを修正しようとはせず、HTMLの構造にも意識したページ作成をしていこうと思います。

**Comment by nametake55** [comment]
* カレンダーのレイアウト崩れが発生した時、CSSのスタイル設定を色々変えてみましたがうまくいきませんでした。
なぜなら、CSSを適用するHTMLの構造にそもそも問題があったからです。

* 修正前のHTMLはこうなっていた。
[図]

* 今回の施策では、CSSを適用するタイミングで、赤と緑の枠の間にパディングをあてる必要がでてきた。
もともとのHTMLの階層が異なっていたために、Bには緑の階層が存在しなかった。
そのため、A、B共通のスタイルを、HTMLの同じ階層にあてることができなかった。

* 今回のような状態で、HTMLの構造を修正しないままCSSで何とかしようとすると・・・
見た目だけ同じにしようとCSSがぐちゃぐちゃになる。

**Comment by oha-ryo-y2i** [comment]
@nametake55 @ykk-yos1982 @keisukeKarino 

はてなブログに下書きを作成しました。
ご確認お願い致します。
