### ISSUE TITLE
チーム3：レイアウト作成(PC)

### ISSUE THREAD

**Issue by ykk-yos1982** [ykk-yos1982/yayoi#5]
デザインカンプに従ってPCサイズのHTML/CSSモックを作成する

**Comment by ghost** [comment]
てすと

**Comment by ghost** [comment]
floatで作ってみたhtml/cssを追加しました。flex版は植竹さんが作ってくれるはず！
対応未定ですが課題としては以下のとおりです。
 - サイズ可変の領域内で文字列を垂直方向（縦書きの場合は水平方向）に中央寄せする方法がわからない。むずい。
 - IE11(Win7)だけPCサイズで水平方向リサイズに追従しない。なぜかコンテンツ2の高さをパーセント指定にすると追従するようになるが、垂直方向リサイズ時の再描画タイミングがかなりおかしい。なんなの。
