### ISSUE TITLE
カレンダートレーニングブログ（後半

### ISSUE THREAD

**Issue by oha-ryo-y2i** [ykk-yos1982/yayoi#52]
@keisukeKarino @nametake55 
遅れて申し訳ありません。
カレンダートレーニングブログの後半を作成しました。

以下のレビュー観点で、初稿レビューをお願いします。
・流れがわかりやすいこと
・大筋の内容に間違いがないこと
・運営チームとして記載してほしい内容が記載されていること

**Comment by oha-ryo-y2i** [comment]
こんにちは、最近ボルダリングをサボりがちなエンジニアのR.Oです！

カレンダートレーニングの後半記事です。
まずは前半の記事から期間が空いてしまったことをお詫び申し上げます。

## 前回の記事概要
前回（URL）は、カレンダーを一先ず完成させました。
<カレンダー画像>
そこで得た学びは「事前のHTML設計が予期せぬレイアウト崩れを防ぐ」です。
HTML作成とCSS適用の作業を交互に行う手間を減らすためにはHTML設計が重要であることを痛感しました。

## 今回の記事概要
今回は、カレンダートレーニングの完成報告（レビュー指摘対応）とフロントエンジニア強化施策全体を通して得た学びや気づきについて報告します。

## カレンダー完成報告
前回作成したカレンダーに対して運営チームからレビュー指摘があったので、指摘対応して完成させました。指摘内容は、主に以下の２点です。
1. クラス名がBEMに則っていない
1. レスポンシブ対応してみよう

一つずつ対応していきましょう

### クラス名がBEMに則っていない
BEMは今回の施策を通して身につけたいと考えていたものですが、クラス名がおかしいよと指摘されました。（BEMの概要やメリットについては前半の記事<url>を参照してください。）
BEMは「block」、「element」、「modifier」という3つの概念をアンスコやハイフンで繋げることでクラス名を作ります。
> 「block\__element--modifier」
という感じです。
しかし、以下の名前のクラスを作ったことが問題でした。「block\__element__element--modifier」
各概念はクラス名の中に一つまでだそうです。

### レスポンシブ対応
前回作成したカレンダーは卓上カレンダーを原寸大で再現しただけなので、レスポンシブ対応しようと指示されました。
弥生のマイポータルWeb(URL)でも今年の春にレスポンシブ対応しましたし、最近のWebサービスでは当たり前になりましたもんね。

#### 実現イメージ
レスポンシブデザインの実現イメージですが、ウィンドウサイズによって以下の三段階のレイアウトに変わるようにします。

1. サイズ大：作成元となったカレンダーの原寸大を再現したレイアウト（前回作ったサイズ）
1. サイズ中：レイアウトのベースはサイズ大と同じだが、ウィンドウサイズによってカレンダーの枠や文字のサイズが変わる
1. サイズ小：作成元となったカレンダーの上部に配置されている小さなカレンダーを再現したレイアウト

#### 実現に必要なもの
今回レスポンシブ対応を実現するにあたって利用したのは、メディアクエリとflexboxです。
まずメディアクエリを使い、３つのウィンドウサイズ毎にCSSを適用できるようにしました。
そしてflexboxプロパティを３に別れたCSSのそれぞれで設定することで、カレンダーの各要素のデザインが動的に変わることを実現しました


### 完成したカレンダー
以上のレビュー指摘対応でカレンダーは完成です！
各ウィンドウサイズのレイアウトはこちらです。

ウィンドウサイズ大
画像１

ウィンドウサイズ中
画像２

ウィンドウサイズ小
画像３

「ウィンドウサイズ中」については、ウィンドウサイズを変えることで各要素のサイズもリアルタイムで変わります。
こちらのパスからHTMLとCSSをダウンロードしてブラウザから開くことで確認してください。

## フロントエンジニア強化施策を通して得た学び
今回のカレンダートレーニングの終了をもって、フロントエンジニア強化施策の第二弾は終了です。
そこで、この施策を通して得た学びをまとめたいと思います。

### 施策参加時に習得したいと思っていたスキル
4.のSass以外のスキルは本施策を通して身につけることが出来ました。
1. HTMLとCSSの基礎
「HTMLタグを作成→CSSを適用」を様々なバリエーションで経験することができたことで、様々な種類の項目が配置されたページを作成できるスキルが身についた。
また、疑似クラスを理解したことで簡単な動的ページをJavaScriptなしに作れるようになった。
1. flexbox
要素同士を並べるレイアウトを簡単に作れるスキルと、レスポンシブ対応の方法を身につけた。
1. BEM(MindBEMding)
クラス名を見るだけでなんのためのHTMLタグなのかすぐに判別できるようになり、HTML作成やCSS適用の作業効率が上がった。
1. Sass
今回はスケジュールの関係上利用することができなかったが、業務では利用する機会があったためそちらで学習中。BEMとの親和性が非常に高いことに気付き、BEMには色々なメリットがあるだなーと再認識。

### 上記以外の学び・気付き
1. HTML設計の重要性
詳細は　前半の記事を参照してください。
1. ペアプロの効果
最初はペアプロに対して「普段関わりのないメンバーと仲良くなれればいいな」程度にしか思っていなかったが、実際にやってみると色々なメリットがあった。
スキルや知識の共有できる、躓いた際に二倍アイデアがでる、連帯感が生まれ、モチベーションが上がる、一人でやるより楽しい、などなど...
そして今回は未熟ながらもドライバー（指示する方）を担当したが、人に教えるという貴重な経験をすることが出来た。

## 総括
弥生ではこれからWebサービスを拡張していく予定なので、今回身につけたスキルや知識をゴリゴリ活用していきたいです。
また、今回はほぼ使用しなかったですが、Javascriptも使ったリッチなページ作りにも挑戦していこうと思います。

**Comment by nametake55** [comment]
～レビュー途中メモ～
#### カレンダー完成報告
* レビュー指摘を受けて、どう修正したかも必要だが、何が難しかったか、どう考えたかを書けるといい
#### 上記以外の学び・気付き
* ペアプロの効果については、そのメリットについて具体例を1つ出して説明したほうがよいかも
（一般的なペアプロのメリットを羅列したように見えないように）
→あと、成果発表の時に話していた、「最初は各自でおこなって、後からペアでやるとよいかも」という感想も入れてもいいかも

**Comment by nametake55** [comment]
施策第2回の締めのブログとするかは確認中。

### 締めのブログとなる場合の対応（案）  
* ブログタイトル
特に2回目終了の旨をタイトルに入れる必要はない  
* 総括の最後に、以下のように1文を入れてもらう
弥生ではこれからWebサービスを拡張していく予定なので、今回身につけたスキルや知識をゴリゴリ活用していきたいです。
今回のカレンダートレーニングで、フロント施策第2回のトレーニングは完了となりました。
施策の中ではほぼ使用しなかったですが、Javascriptも使ったリッチなページ作りにも挑戦していこうと思います。

**Comment by oha-ryo-y2i** [comment]
こんにちは、近頃体重が増えたせいで趣味のボルダリングに支障を来しているエンジニアのR.Oです！  
  
現在引っ越しを検討しているのですが、検討先の家のすぐ近くにボルダリングジムがあることを知り、「通いすぎて上達しちゃうかな～」と妄想することが最近のマイブームです。

# ★宣伝★12/21（木）に社外向け勉強会を開催します。
冒頭からタイトルと関係がなくてすみませんm(_ _)m    

弥生では毎月第３木曜日の夜に外部のエンジニア向けの勉強会「もくテク」を開催しているのですが、今月も開催するのでその宣伝です。  
今回の勉強会のタイトルは「弥生のフロントシステムって？～UX向上と品質改善の取り組みについて～」です。  

以下のURLから詳細の参照と参加が可能なのでご興味のある方は是非！！  

https://mokuteku.connpass.com/event/73499/

弥生が取り組んだUX改善や品質改善、ヒートマップを使った自社サービス解析などについてのセッションを行う予定で、
私R.Oも「AWSを使ったメッセージングサービスの性能改善で苦労したこと」についてのセッションを行う予定です。

# カレンダートレーニング完了報告（＆フロントエンジニア強化施策全体の振り返り）
関係ない話が長くなりましたが、カレンダートレーニングの後半記事です。  
と、その前に前半の記事から大きく期間が空いてしまったことをお詫び申し上げます。

## 前回の内容

[前回](http://tech.yayoi-kk.co.jp/entry/2017/08/30/173836)は、カレンダーを一先ず完成させました。  
![2017-12-05_184524](https://user-images.githubusercontent.com/26620507/33711829-b4e4828c-db88-11e7-97fc-e1cbf5d92719.jpg)

そこで得た学びは「事前のHTML設計が予期せぬレイアウト崩れを防ぐ」です。  
HTML作成とCSS適用の作業を交互に行う手間を減らすためにはHTML設計が重要であることを痛感しました。

## 今回の内容
今回は、カレンダートレーニングの完成報告と、フロントエンジニア強化施策全体を通して得た学びや気づきについて報告します。

## カレンダー完成報告
前回作成したカレンダーに対する運営チームからレビュー指摘があったので、対応して完成させました。  
指摘内容は、主に以下の２点です。  
1. クラス名がBEMに則っていない
1. レスポンシブ対応してみよう

### クラス名がBEMに則っていない
BEMは「block」、「element」、「modifier」という3つの概念をアンスコやハイフンで繋げることでクラス名を作るのですが、「各概念はクラス名の中に一つまで」というルールに違反するクラス名がいくつか存在したため修正しました。  
今後は以下の形式以外の名前をクラスにつけないように気をつけます。
> 「block」  
> 「block\__element」  
> 「block--modifier」  
> 「block\__element--modifier」  

※BEMの概要やメリットについては[前回の記事](http://tech.yayoi-kk.co.jp/entry/2017/08/30/173836)を参照してください。  

### レスポンシブ対応
前回作成したカレンダーは卓上カレンダーを原寸大で再現しただけなので、レスポンシブ対応してみようと指示されました。
レスポンシブ対応とは一言でいえば、ブラウザのサイズによってレイアウトがイイ感じに変わる画面のことです。  
最近のWebサービスではレスポンシブ対応していることが当たり前になっていて、弥生のポータルサイト[マイポータルWeb](https://myportal.yayoi-kk.co.jp/)でも今年の春に対応しました。
※マイポータルWebはログインが必要ですが、ログイン画面もレスポンシブ対応しています。

#### 実現イメージ
レスポンシブデザインの実現イメージですが、ウィンドウサイズによって以下の三段階のレイアウトに変わるようにします。

1. ウィンドウサイズ大(横530px以上&縦710px以上)：卓上カレンダーを原寸大で再現
1. ウィンドウサイズ中(横380px以上&縦530px以下 or 横710px以下&縦380px以上)：ウィンドウサイズによって要素のサイズが動的に変わる
1. ウィンドウサイズ小(横380px以下&縦380px以下：作成元となったカレンダーの上部に配置されている小さなカレンダーを再現
![20170818194656](https://user-images.githubusercontent.com/26620507/33713119-4d274580-db8d-11e7-9637-51cb6d9c32f4.jpg)

#### 実現に必要なもの
今回レスポンシブ対応を実現するにあたって利用したのは、CSSのメディアクエリとflexboxです。
1. メディアクエリを使って３つのウィンドウサイズ毎にCSSを適用できるようにする
1. ３つのウィンドウサイズ毎にflexboxプロパティを適用する
これでウィンドウサイズによって各要素が動的に変わるようになりました。

### 完成したカレンダー
以上の対応でカレンダーは完成です！
各ウィンドウサイズのレイアウトはこちらです。

ウィンドウサイズ大

![2017-12-05_184524](https://user-images.githubusercontent.com/26620507/33711846-c1baf91e-db88-11e7-8670-0d05dca1f5dc.jpg)

ウィンドウサイズ中

![2017-12-05_184518](https://user-images.githubusercontent.com/26620507/33711849-c4e92bd8-db88-11e7-99bd-8c6dff91cfcc.jpg)

ウィンドウサイズ小

![2017-12-05_184511](https://user-images.githubusercontent.com/26620507/33711853-c78d736c-db88-11e7-9b16-6573d2224358.jpg)

ソースコードは[こちら](https://github.com/ykk-yos1982/yayoi/tree/master/20170710/team_4)からダウンロードできます。
※マルチブラウザ対応していないので、**必ずGoogle Chromeで確認してください。**

# フロントエンジニア強化施策を通して得たこと
今回のカレンダートレーニングの終了をもって、フロントエンジニア強化施策の第二弾は終了です。  
施策全体を通して得た学びもまとめたいと思います。　  

## 施策参加時に習得したいと思っていたスキル
4.のSass以外のスキルは本施策を通して身につけることが出来ました。

1. HTMLとCSSの基礎
主要なHTMLタグやCSSプロパティを使えるようになった。疑似クラスを使えばJavaScriptなしでイベントハンドラを作成できるのは目から鱗だった
1. flexbox
要素を並べることやレスポンシブ対応が簡単に実現できてすごいと思いました。（小並感）
ただし、バグが存在するようなので過信は禁物
詳しくは[コチラの記事](https://qiita.com/hashrock/items/189db03021b0f565ae27)などを参照
1. BEM(MindBEMding)
クラス名だけでどういうつもりで作ったHTMLタグなのかがすぐに判別できるようになり、HTML作成やCSS適用の作業効率が上がった
1. Sass
今回はスケジュールの関係上利用することができなかったが、業務で利用する機会があり学習中。BEMとの親和性が非常に高い

## 気付き
### ペアプロの効果
当初は「普段関わりのないメンバーと仲良くなれるきっかけになるな」程度にしか思っていなかったのですが、多くのメリットがありました。
- お互いのスキルや知識の把握と共有がスムーズになる
例：詰まったらすぐ相手に分かるので、後輩の「わからないけど聞きにくいな」や先輩の「ちゃんと理解できているのかな」が防げるし、その場で答えを教えることもできる。
- ナビゲータは、人に指示したり教えることを経験できる
- ドライバは、一人では気付くのに時間がかかる「勘所」や「経験者にとっての常識」をナビゲータから教わることができる
→初めてだと「CSSが想定通りに適用されないと思ったらIEだった」や「vertical-alignが効かないと思ったら対象がインライン要素だった」などで大きくハマってしまう
- 責任感や連帯感によりモチベーションが上がる

ただし、ペアプロでの開発のみだけではなく、ドライバ一人での開発もたまにさせたほうが一人で達成する力などが見に付いていいのかなと思いました。（ナビゲータのハンドリングが上手ければ必要ないかも？？）

## 総括
弥生はこれからWebサービスを拡張していく予定なので、今回身につけたフロントエンド開発のスキルや知識をゴリゴリ活用していきたいです。
弥生ではこれからWebサービスを拡張していく予定なので、今回身につけたスキルや知識をゴリゴリ活用していきたいです。
今回のカレンダートレーニングで、フロント施策第2回のトレーニングは完了となりました。
施策の中ではほぼ使用しなかったですが、Javascriptも使ったリッチなページ作りにも挑戦していこうと思います。

###　今後について
また、別のテーマで記事を投稿していこうと思いますので、引き続きよろしくお願い致します！

**Comment by oha-ryo-y2i** [comment]
@YYItrmk   @nametake55 
レビュー指摘を反映と木テクの宣伝追加しました。再レビューお願い致します。
可読性がよくなるように前半の記事よりボリュームを敢えて少なくしているので、内容が薄いと感じた場合は教えてください。

 -------------------------

こんにちは、近頃体重が増えたせいで趣味のボルダリングに支障を来しているエンジニアのR.Oです！  
  
現在引っ越しを検討しているのですが、検討先の家のすぐ近くにボルダリングジムがあることを知り、「通いすぎて上達しちゃうかな～」と妄想することが最近のマイブームです。

# ★宣伝★12/21（木）に社外向け勉強会を開催します。
冒頭からタイトルと関係がなくてすみませんm(_ _)m    

弥生では毎月第３木曜日の夜に外部のエンジニア向けの勉強会「もくテク」を開催しているのですが、今月も開催するのでその宣伝です。  
今回の勉強会のタイトルは「弥生のフロントシステムって？～UX向上と品質改善の取り組みについて～」です。  

以下のURLから詳細の参照と参加が可能なのでご興味のある方は是非！！  

https://mokuteku.connpass.com/event/73499/

セッション内容は、弥生が取り組んだUX改善や品質改善、ヒートマップを使った自社サービス解析などを予定していて、
私R.Oも「AWSを使ったメッセージングサービスの性能改善で苦労したこと」について発表します。

# カレンダートレーニング完了報告
本題のカレンダートレーニングの後半についてです。  
と、その前に前半の記事から大きく期間が空いてしまったことをお詫び申し上げます。

## 前回の内容

[前回](http://tech.yayoi-kk.co.jp/entry/2017/08/30/173836)は、カレンダーを一先ず完成させました。  
![2017-12-05_184524](https://user-images.githubusercontent.com/26620507/33711829-b4e4828c-db88-11e7-97fc-e1cbf5d92719.jpg)

そこで得た学びは「事前のHTML設計が予期せぬレイアウト崩れを防ぐ」です。  
HTML作成とCSS適用の作業を交互に行う手間を減らすためにはHTML設計が重要であることを痛感しました。

## 今回の内容
今回は、カレンダートレーニングの完成報告と、フロントエンジニア強化施策全体を通して得た学びや気づきについて報告します。

## カレンダー完成報告
前回作成したカレンダーに対する運営チームからレビュー指摘があったので、対応して完成させました。  
指摘内容は、主に以下の２点です。  
1. クラス名がBEMに則っていない
1. レスポンシブ対応してみよう

### クラス名がBEMに則っていない
BEMは「block」、「element」、「modifier」という3つの概念をアンスコやハイフンで繋げることでクラス名を作るのですが、「各概念はクラス名の中に一つまで」というルールに違反するクラス名がいくつか存在したため修正しました。  
今後は以下の形式以外の名前をクラスにつけないように気をつけます。
> 「block」  
> 「block\__element」  
> 「block--modifier」  
> 「block\__element--modifier」  

※BEMの概要やメリットについては[前回の記事](http://tech.yayoi-kk.co.jp/entry/2017/08/30/173836)を参照してください。  

### レスポンシブ対応
前回作成したカレンダーは卓上カレンダーを原寸大で再現しただけなので、レスポンシブ対応してみようと指示されました。
レスポンシブ対応とは一言でいえば、ブラウザのサイズによってレイアウトがイイ感じに変わる画面のことです。  
最近のWebサービスではレスポンシブ対応していることが当たり前になっていて、弥生のポータルサイト[マイポータルWeb](https://myportal.yayoi-kk.co.jp/)でも今年の春に対応しました。
※マイポータルWebはログインが必要ですが、ログイン画面もレスポンシブ対応しています。

#### 実現イメージ
レスポンシブデザインの実現イメージですが、ウィンドウサイズによって以下の三段階のレイアウトに変わるようにします。

1. ウィンドウサイズ大(横530px以上&縦710px以上)：卓上カレンダーを原寸大で再現
1. ウィンドウサイズ中(横380px以上&縦530px以下 or 横710px以下&縦380px以上)：ウィンドウサイズによって要素のサイズが動的に変わる
1. ウィンドウサイズ小(横380px以下&縦380px以下：作成元となったカレンダーの上部に配置されている小さなカレンダーを再現
![20170818194656](https://user-images.githubusercontent.com/26620507/33713119-4d274580-db8d-11e7-9637-51cb6d9c32f4.jpg)

#### 実現に必要なもの
今回レスポンシブ対応を実現するにあたって利用したのは、CSSのメディアクエリとflexboxです。
以下の手順でウィンドウサイズによって各要素のサイズを動的に変えることができました。
1. メディアクエリを使って３つのウィンドウサイズ毎にCSSを適用できるようにする
1. ３つのウィンドウサイズ毎にflexプロパティを適用する

### 完成したカレンダー
以上の対応でカレンダーは完成です！
各ウィンドウサイズのレイアウトはこちらです。

ウィンドウサイズ大

![2017-12-05_184524](https://user-images.githubusercontent.com/26620507/33711846-c1baf91e-db88-11e7-8670-0d05dca1f5dc.jpg)

ウィンドウサイズ中

![2017-12-05_184518](https://user-images.githubusercontent.com/26620507/33711849-c4e92bd8-db88-11e7-99bd-8c6dff91cfcc.jpg)

ウィンドウサイズ小

![2017-12-05_184511](https://user-images.githubusercontent.com/26620507/33711853-c78d736c-db88-11e7-9b16-6573d2224358.jpg)

ソースコードは[こちら](https://github.com/ykk-yos1982/yayoi/tree/master/20170710/team_4)からダウンロードできます。
※マルチブラウザ対応していないので、**必ずGoogle Chromeで確認してください。**

# フロントエンジニア強化施策を通して得たこと
今回のカレンダートレーニングの終了をもって、フロントエンジニア強化施策の第二弾は終了です。  
施策全体を通して得た学びもまとめたいと思います。　  

## 施策参加時に習得したいと思っていたスキル
4.のSass以外のスキルは本施策を通して身につけることが出来ました。

1. HTMLとCSSの基礎
主要なHTMLタグやCSSプロパティを使えるようになった。疑似クラスを使えばJavaScriptなしでhoverやfocusを感知してレイアウトを動的に変更できるのは目から鱗だった。
1. flexbox
flexboxを使うだけで、要素を並べることやレスポンシブ対応が簡単に実現できるようになった。
ただし、バグが存在するようなので過信は禁物。詳しくは[コチラの記事](https://qiita.com/hashrock/items/189db03021b0f565ae27)などを参照
1. BEM(MindBEMding)
クラスの命名にBEMを使うことでHTML構造がひと目でわかるようになるので、可読性や保守性の高いHTMLを作ることができるようになった。
1. Sass
今回はスケジュールの関係上利用することができなかったが、業務で機会があったので学習中。BEMとの親和性が高いことに感動した。

## 気付き
### ペアプロの効果
当初は「普段関わりのないメンバーと仲良くなれるきっかけになるな」程度にしか思っていなかったのですが、多くのメリットがありました。
- お互いのスキルや知識の把握と共有がスムーズになる
例：躓いたらすぐ相手に分かるので、後輩の「わからないけど聞きにくい」や先輩の「ちゃんと理解できているのかな」が防げるし、なによりその場で正解を教えることができる。
- ナビゲータは、人に指示したり教えることを経験できる
- ドライバは、一人では気付くのに時間がかかる「勘所」や「経験者にとっての常識」をナビゲータから教わることができる
→初心者が「CSSが想定通りに適用されない原因がブラウザだった」などで大きくハマってしまうのはあるある
- 責任感や連帯感によりモチベーションが上がる
などなど...
ただし、ペアプロでの開発のみだけではなく、ドライバ一人での開発もさせたほうが一人で達成する力などが身に付いていいのかなと思いました。（ナビゲータのハンドリングが上手ければ必要ないかも？？）

## 総括
今回報告したカレンダートレーニングで、フロントエンジニア強化施策第二回は完了となりました。
弥生はこれからWebサービスを拡張していく予定なので、今回身につけたフロントエンド開発のスキルや知識をゴリゴリ活用していくつもりです。
また、施策の中ではほぼ使用しなかったJavascriptも使ってリッチなWebサービスを目指していきます。

### 今後について
フロントエンド関連以外のテーマでも記事を投稿していきたいと思っているので、引き続きよろしくお願い致します！

**Comment by nametake55** [comment]
# 指摘

## カレンダートレーニング完了報告
* "と、その前に前半の記事から大きく期間が空いてしまったことをお詫び申し上げます。"
→ちょっと固い感じがする。なくてもいいかも。

## レスポンシブ対応
* レスポンシブ対応とは一言でいえば、ブラウザのサイズによってレイアウトがイイ感じに変わる画面のことです。
→"レイアウトがイイ感じに"をもう少しだけ具体的に書くか、下の「完成したカレンダー」を参照してもらうような記載にしたほうがいい。

例えば・・
レスポンシブ対応とは、"1つのHTMLで、複数ブラウザのサイズに合わせた画面表示を実現できる手法。"堅苦しいので一言で言うと、・・とつなげるとか

## 施策参加時に習得したいと思っていたスキル
* flexbox
「レスポンシブ対応が簡単に」について、学んだ事の詳細をもう一言付け加えるほうがいい。
何が簡単だったか

* BEM(MindBEMding)
若干BEMのメリットになってしまっている？
BEMの使い方を理解したうえで、HTMLの構造化→結果、可読性や保守性の高いHTMLとなったのでは？
（HTMLの構造がうまくいってなくても、BEMに沿って無理やりクラス名つけることはできる。）

HTMLの構造化がヘタだとBEMの命名規則に従って名前がつけにくい。→結果BEMを使うことによって、HTMLの構造化を考えられるようになった。
とか。

修正前の内容↓のほうが、具体性があったかも。
"クラス名を見るだけでなんのためのHTMLタグなのかすぐに判別できるようになり、HTML作成やCSS適用の作業効率が上がった。"

## ペアプロの効果
* 今回の施策ではペアプロを行った という前置きを一言入れたほうがいい。

* 責任感や連帯感によりモチベーションが上がる
→ペアで成果物を仕上げるという責任感？ペアの人にしっかりと教えなくてはという責任感？

## その他
* JavaScriptとJavascriptの表記ゆれ

**Comment by oha-ryo-y2i** [comment]
@nametake55 
レビュー指摘を反映したものを、はてなブログで下書きとして作成しました。
最終確認をお願い致します。

https://blog.hatena.ne.jp/yayoiTech/yayoitech.hatenablog.com/drafts

**Comment by oha-ryo-y2i** [comment]
ブログ公開しました。
クローズします。
