### ISSUE TITLE
アウトプット_藤井

### ISSUE THREAD

**Issue by SatokoFujii0119** [ykk-yos1982/yayoi#7]
## フェーズ1
1. つまづいたこと
    - viewportの設定忘れ
    - コンテンツのまとめ方
       - どうまとめるのかわからない
       - コンテンツ2とコンテンツ3,4,5をどうわければいいのか
    - flex boxの使い方
       - 横並び以外をどの単位に対して行うのか
    - 縦書きを中央に配置する方法
    - Firefoxでflex boxの設定を確認すると、コンテンツ4,5が消える
       - Chromeなら確認できる
    - 高さ調整
      - コンテンツの高さが画面サイズよりも大きくなってしまう

2. 不明点
    - メディアクエリの設定をブラウザを動かして、コンテンツが並ぶ箇所で設定したがもっとうまい方法はないのか

3. 参考サイト
<http://coliss.com/articles/build-websites/operation/css/css3-flexbox-properties-by-scotch.html>
<http://www.html5-memo.com/css3/mediaqueries-sample01/>

## フェーズ2

**Comment by SatokoFujii0119** [comment]
フェーズ1でつまづいたことを追記しました。

**Comment by nametake55** [comment]
フロントエンジニア強化施策 第2回開催のため、第1回のissueはクローズします。
